#include "../macros.h"
#include "../rstack.h"
#include <assert.h>

int main(void) {
    rstack_t* rs0 = rstack_new();
    rstack_t* rs1 = rstack_new();
    rstack_t* rs2 = rstack_new();
    rstack_t* rs3 = rstack_new();
    rstack_t* rs4 = rstack_new();
    rstack_t* rs5 = rstack_new();
    rstack_t* rs6 = rstack_new();
    rstack_t* rs7 = rstack_new();
    rstack_t* rs8 = rstack_new();
    rstack_t* rs9 = rstack_new();
    rstack_t* rs10 = rstack_new();
    rstack_t* rs11 = rstack_new();
    rstack_t* rs12 = rstack_new();
    rstack_t* rs13 = rstack_new();
    rstack_t* rs14 = rstack_new();
    rstack_t* rs15 = rstack_new();
    rstack_t* rs16 = rstack_new();
    rstack_t* rs17 = rstack_new();
    rstack_t* rs18 = rstack_new();
    rstack_t* rs19 = rstack_new();
    rstack_t* rs20 = rstack_new();
    rstack_t* rs21 = rstack_new();
    rstack_t* rs22 = rstack_new();
    rstack_t* rs23 = rstack_new();
    rstack_t* rs24 = rstack_new();
    rstack_t* rs25 = rstack_new();
    rstack_t* rs26 = rstack_new();
    rstack_t* rs27 = rstack_new();
    rstack_t* rs28 = rstack_new();
    rstack_t* rs29 = rstack_new();
    rstack_t* rs30 = rstack_new();
    rstack_t* rs31 = rstack_new();
    rstack_t* rs32 = rstack_new();
    rstack_t* rs33 = rstack_new();
    rstack_t* rs34 = rstack_new();
    rstack_t* rs35 = rstack_new();
    rstack_t* rs36 = rstack_new();
    rstack_t* rs37 = rstack_new();
    rstack_t* rs38 = rstack_new();
    rstack_t* rs39 = rstack_new();
    rstack_t* rs40 = rstack_new();
    rstack_t* rs41 = rstack_new();
    rstack_t* rs42 = rstack_new();
    rstack_t* rs43 = rstack_new();
    rstack_t* rs44 = rstack_new();
    rstack_t* rs45 = rstack_new();
    rstack_t* rs46 = rstack_new();
    rstack_t* rs47 = rstack_new();
    rstack_t* rs48 = rstack_new();
    rstack_t* rs49 = rstack_new();
    rstack_t* rs50 = rstack_new();
    rstack_t* rs51 = rstack_new();
    rstack_t* rs52 = rstack_new();
    rstack_t* rs53 = rstack_new();
    rstack_t* rs54 = rstack_new();
    rstack_t* rs55 = rstack_new();
    rstack_t* rs56 = rstack_new();
    rstack_t* rs57 = rstack_new();
    rstack_t* rs58 = rstack_new();
    rstack_t* rs59 = rstack_new();
    rstack_t* rs60 = rstack_new();
    rstack_t* rs61 = rstack_new();
    rstack_t* rs62 = rstack_new();
    rstack_t* rs63 = rstack_new();
    rstack_t* rs64 = rstack_new();
    rstack_t* rs65 = rstack_new();
    rstack_t* rs66 = rstack_new();
    rstack_t* rs67 = rstack_new();
    rstack_t* rs68 = rstack_new();
    rstack_t* rs69 = rstack_new();
    rstack_t* rs70 = rstack_new();
    rstack_t* rs71 = rstack_new();
    rstack_t* rs72 = rstack_new();
    rstack_t* rs73 = rstack_new();
    rstack_t* rs74 = rstack_new();
    rstack_t* rs75 = rstack_new();
    rstack_t* rs76 = rstack_new();
    rstack_t* rs77 = rstack_new();
    rstack_t* rs78 = rstack_new();
    rstack_t* rs79 = rstack_new();
    rstack_t* rs80 = rstack_new();
    rstack_t* rs81 = rstack_new();
    rstack_t* rs82 = rstack_new();
    rstack_t* rs83 = rstack_new();
    rstack_t* rs84 = rstack_new();
    rstack_t* rs85 = rstack_new();
    rstack_t* rs86 = rstack_new();
    rstack_t* rs87 = rstack_new();
    rstack_t* rs88 = rstack_new();
    rstack_t* rs89 = rstack_new();
    rstack_t* rs90 = rstack_new();
    rstack_t* rs91 = rstack_new();
    rstack_t* rs92 = rstack_new();
    rstack_t* rs93 = rstack_new();
    rstack_t* rs94 = rstack_new();
    rstack_t* rs95 = rstack_new();
    rstack_t* rs96 = rstack_new();
    rstack_t* rs97 = rstack_new();
    rstack_t* rs98 = rstack_new();
    rstack_t* rs99 = rstack_new();
    NO_ERROR(rstack_write("test_47.fout", rs87));
    NO_ERROR(rstack_write("test_16.fout", rs47));
    ASSERT(rstack_empty(rs26) == true);
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    NO_ERROR(rstack_write("test_15.fout", rs78));
    ASSERT(rstack_empty(rs19) == true);
    NO_ERROR(rstack_push_rstack(rs17, rs98));
    NO_ERROR(rstack_write("test_73.fout", rs97));
    NO_ERROR(rstack_write("test_12.fout", rs43));
    NO_ERROR(rstack_write("test_42.fout", rs36));
    ASSERT_RESULT(rstack_front(rs92), false, 0UL);
    NO_ERROR(rstack_write("test_96.fout", rs45));
    NO_ERROR(rstack_write("test_62.fout", rs54));
    NO_ERROR(rstack_write("test_49.fout", rs42));
    NO_ERROR(rstack_write("test_56.fout", rs33));
    NO_ERROR(rstack_write("test_26.fout", rs93));
    NO_ERROR(rstack_write("test_53.fout", rs25));
    NO_ERROR(rstack_write("test_44.fout", rs1));
    NO_ERROR(rstack_push_rstack(rs22, rs33));
    NO_ERROR(rstack_write("test_19.fout", rs9));
    NO_ERROR(rstack_write("test_80.fout", rs8));
    NO_ERROR(rstack_write("test_23.fout", rs25));
    NO_ERROR(rstack_write("test_24.fout", rs22));
    NO_ERROR(rstack_write("test_74.fout", rs74));
    NO_ERROR(rstack_write("test_41.fout", rs8));
    NO_ERROR(rstack_write("test_33.fout", rs50));
    NO_ERROR(rstack_write("test_81.fout", rs34));
    NO_ERROR(rstack_write("test_28.fout", rs83));
    NO_ERROR(rstack_write("test_8.fout", rs15));
    NO_ERROR(rstack_write("test_13.fout", rs10));
    NO_ERROR(rstack_write("test_78.fout", rs13));
    NO_ERROR(rstack_write("test_88.fout", rs27));
    NO_ERROR(rstack_write("test_94.fout", rs40));
    ASSERT(rstack_empty(rs62) == true);
    NO_ERROR(rstack_write("test_52.fout", rs14));
    NO_ERROR(rstack_write("test_4.fout", rs47));
    NO_ERROR(rstack_write("test_77.fout", rs95));
    NO_ERROR(rstack_write("test_95.fout", rs96));
    NO_ERROR(rstack_write("test_27.fout", rs9));
    NO_ERROR(rstack_write("test_67.fout", rs6));
    NO_ERROR(rstack_write("test_75.fout", rs22));
    NO_ERROR(rstack_write("test_31.fout", rs5));
    NO_ERROR(rstack_push_rstack(rs24, rs45));
    NO_ERROR(rstack_write("test_83.fout", rs48));
    NO_ERROR(rstack_write("test_40.fout", rs28));
    NO_ERROR(rstack_push_rstack(rs87, rs62));
    NO_ERROR(rstack_write("test_45.fout", rs94));
    NO_ERROR(rstack_write("test_30.fout", rs78));
    NO_ERROR(rstack_write("test_86.fout", rs16));
    NO_ERROR(rstack_write("test_10.fout", rs23));
    NO_ERROR(rstack_write("test_3.fout", rs93));
    NO_ERROR(rstack_write("test_48.fout", rs22));
    NO_ERROR(rstack_write("test_5.fout", rs89));
    NO_ERROR(rstack_write("test_35.fout", rs16));
    NO_ERROR(rstack_write("test_11.fout", rs68));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs85, rs97));
    ASSERT_RESULT(rstack_front(rs31), false, 0UL);
    NO_ERROR(rstack_write("test_34.fout", rs20));
    NO_ERROR(rstack_write("test_98.fout", rs49));
    NO_ERROR(rstack_write("test_87.fout", rs17));
    NO_ERROR(rstack_write("test_37.fout", rs29));
    NO_ERROR(rstack_write("test_71.fout", rs61));
    NO_ERROR(rstack_write("test_99.fout", rs76));
    NO_ERROR(rstack_push_rstack(rs29, rs66));
    NO_ERROR(rstack_write("test_58.fout", rs39));
    ASSERT_RESULT(rstack_front(rs96), false, 0UL);
    NO_ERROR(rstack_write("test_32.fout", rs44));
    NO_ERROR(rstack_write("test_57.fout", rs80));
    NO_ERROR(rstack_write("test_97.fout", rs77));
    NO_ERROR(rstack_write("test_91.fout", rs7));
    NO_ERROR(rstack_write("test_90.fout", rs7));
    NO_ERROR(rstack_push_rstack(rs52, rs15));
    NO_ERROR(rstack_write("test_25.fout", rs42));
    NO_ERROR(rstack_write("test_89.fout", rs47));
    NO_ERROR(rstack_write("test_59.fout", rs43));
    NO_ERROR(rstack_write("test_38.fout", rs15));
    NO_ERROR(rstack_write("test_85.fout", rs1));
    NO_ERROR(rstack_push_rstack(rs21, rs77));
    NO_ERROR(rstack_write("test_51.fout", rs44));
    NO_ERROR(rstack_write("test_70.fout", rs31));
    NO_ERROR(rstack_push_rstack(rs56, rs10));
    NO_ERROR(rstack_write("test_9.fout", rs98));
    NO_ERROR(rstack_write("test_76.fout", rs79));
    NO_ERROR(rstack_write("test_29.fout", rs63));
    NO_ERROR(rstack_write("test_2.fout", rs5));
    NO_ERROR(rstack_push_rstack(rs15, rs95));
    NO_ERROR(rstack_push_rstack(rs42, rs10));
    NO_ERROR(rstack_write("test_14.fout", rs18));
    NO_ERROR(rstack_write("test_93.fout", rs63));
    NO_ERROR(rstack_write("test_92.fout", rs79));
    NO_ERROR(rstack_write("test_21.fout", rs38));
    NO_ERROR(rstack_write("test_46.fout", rs94));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    NO_ERROR(rstack_write("test_84.fout", rs82));
    NO_ERROR(rstack_write("test_61.fout", rs29));
    NO_ERROR(rstack_write("test_55.fout", rs36));
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    NO_ERROR(rstack_write("test_0.fout", rs88));
    NO_ERROR(rstack_push_rstack(rs43, rs78));
    NO_ERROR(rstack_write("test_65.fout", rs31));
    NO_ERROR(rstack_write("test_50.fout", rs48));
    NO_ERROR(rstack_push_rstack(rs68, rs55));
    NO_ERROR(rstack_push_rstack(rs63, rs62));
    NO_ERROR(rstack_write("test_22.fout", rs31));
    NO_ERROR(rstack_push_rstack(rs83, rs52));
    NO_ERROR(rstack_write("test_17.fout", rs65));
    NO_ERROR(rstack_write("test_43.fout", rs96));
    NO_ERROR(rstack_push_rstack(rs16, rs31));
    NO_ERROR(rstack_push_rstack(rs60, rs81));
    NO_ERROR(rstack_push_rstack(rs12, rs1));
    NO_ERROR(rstack_write("test_20.fout", rs11));
    ASSERT_RESULT(rstack_front(rs28), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs25, rs99));
    NO_ERROR(rstack_write("test_69.fout", rs15));
    ASSERT_RESULT(rstack_front(rs46), false, 0UL);
    NO_ERROR(rstack_write("test_1.fout", rs59));
    NO_ERROR(rstack_push_rstack(rs46, rs67));
    NO_ERROR(rstack_push_rstack(rs77, rs66));
    NO_ERROR(rstack_write("test_54.fout", rs58));
    NO_ERROR(rstack_write("test_64.fout", rs29));
    NO_ERROR(rstack_push_rstack(rs57, rs40));
    NO_ERROR(rstack_write("test_63.fout", rs92));
    NO_ERROR(rstack_push_rstack(rs7, rs57));
    NO_ERROR(rstack_write("test_82.fout", rs32));
    NO_ERROR(rstack_write("test_39.fout", rs7));
    NO_ERROR(rstack_write("test_36.fout", rs67));
    NO_ERROR(rstack_write("test_68.fout", rs19));
    NO_ERROR(rstack_push_rstack(rs86, rs84));
    NO_ERROR(rstack_write("test_18.fout", rs9));
    NO_ERROR(rstack_write("test_66.fout", rs35));
    NO_ERROR(rstack_push_rstack(rs60, rs47));
    NO_ERROR(rstack_write("test_6.fout", rs80));
    NO_ERROR(rstack_write("test_79.fout", rs88));
    NO_ERROR(rstack_write("test_72.fout", rs31));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_write("test_7.fout", rs40));
    NO_ERROR(rstack_write("test_60.fout", rs86));
    rstack_delete(rs95);
    rstack_delete(rs96);
    rstack_delete(rs97);
    rstack_delete(rs98);
    rstack_delete(rs99);
    ASSERT_RESULT(rstack_front(rs91), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs75, rs41));
    NO_ERROR(rstack_push_rstack(rs72, rs11));
    NO_ERROR(rstack_push_rstack(rs38, rs34));
    NO_ERROR(rstack_push_rstack(rs49, rs8));
    NO_ERROR(rstack_push_rstack(rs3, rs9));
    NO_ERROR(rstack_push_rstack(rs60, rs40));
    NO_ERROR(rstack_push_rstack(rs47, rs50));
    NO_ERROR(rstack_push_rstack(rs46, rs48));
    ASSERT(rstack_empty(rs58) == true);
    NO_ERROR(rstack_push_rstack(rs76, rs55));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs23, rs66));
    NO_ERROR(rstack_push_rstack(rs42, rs78));
    NO_ERROR(rstack_push_rstack(rs37, rs78));
    ASSERT(rstack_empty(rs39) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs45));
    ASSERT_RESULT(rstack_front(rs85), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs31, rs51));
    NO_ERROR(rstack_push_rstack(rs78, rs26));
    ASSERT(rstack_empty(rs57) == true);
    NO_ERROR(rstack_push_rstack(rs83, rs21));
    NO_ERROR(rstack_push_rstack(rs30, rs84));
    NO_ERROR(rstack_push_rstack(rs60, rs7));
    NO_ERROR(rstack_push_rstack(rs58, rs32));
    NO_ERROR(rstack_push_rstack(rs45, rs72));
    ASSERT_RESULT(rstack_front(rs31), false, 0UL);
    ASSERT_RESULT(rstack_front(rs58), false, 0UL);
    ASSERT_RESULT(rstack_front(rs33), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs61, rs56));
    NO_ERROR(rstack_push_rstack(rs87, rs34));
    ASSERT_RESULT(rstack_front(rs77), false, 0UL);
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs91, rs3));
    NO_ERROR(rstack_push_rstack(rs68, rs94));
    ASSERT_RESULT(rstack_front(rs27), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs82, rs76));
    rstack_delete(rs90);
    rstack_delete(rs91);
    rstack_delete(rs92);
    rstack_delete(rs93);
    rstack_delete(rs94);
    ASSERT(rstack_empty(rs79) == true);
    ASSERT(rstack_empty(rs33) == true);
    NO_ERROR(rstack_push_rstack(rs70, rs48));
    NO_ERROR(rstack_push_rstack(rs34, rs83));
    NO_ERROR(rstack_push_rstack(rs71, rs11));
    NO_ERROR(rstack_push_rstack(rs8, rs35));
    NO_ERROR(rstack_push_rstack(rs9, rs34));
    ASSERT(rstack_empty(rs58) == true);
    NO_ERROR(rstack_push_rstack(rs14, rs23));
    NO_ERROR(rstack_push_rstack(rs84, rs57));
    ASSERT_RESULT(rstack_front(rs78), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs75));
    ASSERT(rstack_empty(rs1) == true);
    ASSERT(rstack_empty(rs59) == true);
    NO_ERROR(rstack_push_rstack(rs69, rs85));
    NO_ERROR(rstack_push_rstack(rs1, rs29));
    NO_ERROR(rstack_push_rstack(rs29, rs14));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    ASSERT_RESULT(rstack_front(rs43), false, 0UL);
    ASSERT(rstack_empty(rs67) == true);
    NO_ERROR(rstack_push_rstack(rs17, rs54));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs34, rs38));
    ASSERT_RESULT(rstack_front(rs32), false, 0UL);
    ASSERT(rstack_empty(rs64) == true);
    NO_ERROR(rstack_push_rstack(rs11, rs30));
    NO_ERROR(rstack_push_rstack(rs12, rs52));
    NO_ERROR(rstack_push_rstack(rs60, rs39));
    NO_ERROR(rstack_push_rstack(rs84, rs41));
    NO_ERROR(rstack_push_rstack(rs89, rs14));
    NO_ERROR(rstack_push_rstack(rs4, rs25));
    NO_ERROR(rstack_push_rstack(rs8, rs17));
    NO_ERROR(rstack_push_rstack(rs6, rs10));
    NO_ERROR(rstack_push_rstack(rs88, rs18));
    NO_ERROR(rstack_push_rstack(rs46, rs66));
    NO_ERROR(rstack_push_rstack(rs88, rs4));
    NO_ERROR(rstack_push_rstack(rs6, rs46));
    rstack_delete(rs85);
    rstack_delete(rs86);
    rstack_delete(rs87);
    rstack_delete(rs88);
    rstack_delete(rs89);
    NO_ERROR(rstack_push_rstack(rs43, rs6));
    NO_ERROR(rstack_push_rstack(rs5, rs3));
    ASSERT(rstack_empty(rs83) == true);
    NO_ERROR(rstack_push_rstack(rs9, rs17));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    ASSERT(rstack_empty(rs31) == true);
    ASSERT_RESULT(rstack_front(rs62), false, 0UL);
    ASSERT_RESULT(rstack_front(rs61), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs42, rs0));
    NO_ERROR(rstack_push_rstack(rs58, rs60));
    NO_ERROR(rstack_push_rstack(rs55, rs78));
    NO_ERROR(rstack_push_rstack(rs29, rs54));
    NO_ERROR(rstack_push_rstack(rs27, rs56));
    NO_ERROR(rstack_push_rstack(rs38, rs74));
    ASSERT_RESULT(rstack_front(rs76), false, 0UL);
    ASSERT_RESULT(rstack_front(rs70), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs83, rs7));
    NO_ERROR(rstack_push_rstack(rs9, rs12));
    ASSERT(rstack_empty(rs25) == true);
    ASSERT(rstack_empty(rs55) == true);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT_RESULT(rstack_front(rs77), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs33, rs42));
    NO_ERROR(rstack_push_rstack(rs34, rs84));
    NO_ERROR(rstack_push_rstack(rs74, rs62));
    NO_ERROR(rstack_push_rstack(rs19, rs38));
    NO_ERROR(rstack_push_rstack(rs62, rs76));
    NO_ERROR(rstack_push_rstack(rs26, rs82));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs45, rs28));
    NO_ERROR(rstack_push_rstack(rs29, rs57));
    NO_ERROR(rstack_push_rstack(rs36, rs34));
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs43));
    NO_ERROR(rstack_push_rstack(rs82, rs56));
    NO_ERROR(rstack_push_rstack(rs0, rs77));
    NO_ERROR(rstack_push_rstack(rs30, rs43));
    NO_ERROR(rstack_push_rstack(rs60, rs27));
    rstack_delete(rs80);
    rstack_delete(rs81);
    rstack_delete(rs82);
    rstack_delete(rs83);
    rstack_delete(rs84);
    NO_ERROR(rstack_push_rstack(rs53, rs77));
    ASSERT(rstack_empty(rs20) == true);
    ASSERT_RESULT(rstack_front(rs56), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs28, rs50));
    ASSERT(rstack_empty(rs9) == true);
    NO_ERROR(rstack_push_rstack(rs64, rs21));
    NO_ERROR(rstack_push_rstack(rs62, rs12));
    ASSERT(rstack_empty(rs40) == true);
    ASSERT_RESULT(rstack_front(rs32), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs75, rs12));
    NO_ERROR(rstack_push_rstack(rs33, rs14));
    ASSERT(rstack_empty(rs65) == true);
    ASSERT(rstack_empty(rs73) == true);
    ASSERT(rstack_empty(rs19) == true);
    ASSERT_RESULT(rstack_front(rs23), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs18, rs71));
    NO_ERROR(rstack_push_rstack(rs61, rs79));
    NO_ERROR(rstack_push_rstack(rs69, rs77));
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs51, rs25));
    NO_ERROR(rstack_push_rstack(rs5, rs52));
    NO_ERROR(rstack_push_rstack(rs55, rs36));
    NO_ERROR(rstack_push_rstack(rs71, rs78));
    NO_ERROR(rstack_push_rstack(rs14, rs6));
    NO_ERROR(rstack_push_rstack(rs8, rs67));
    NO_ERROR(rstack_push_rstack(rs12, rs57));
    NO_ERROR(rstack_push_rstack(rs1, rs29));
    ASSERT(rstack_empty(rs50) == true);
    NO_ERROR(rstack_push_rstack(rs54, rs63));
    NO_ERROR(rstack_push_rstack(rs77, rs2));
    ASSERT_RESULT(rstack_front(rs21), false, 0UL);
    ASSERT_RESULT(rstack_front(rs34), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs77, rs78));
    NO_ERROR(rstack_push_rstack(rs64, rs46));
    NO_ERROR(rstack_push_rstack(rs55, rs41));
    NO_ERROR(rstack_push_rstack(rs9, rs0));
    NO_ERROR(rstack_push_rstack(rs23, rs3));
    NO_ERROR(rstack_push_rstack(rs74, rs40));
    rstack_delete(rs75);
    rstack_delete(rs76);
    rstack_delete(rs77);
    rstack_delete(rs78);
    rstack_delete(rs79);
    NO_ERROR(rstack_push_rstack(rs6, rs36));
    NO_ERROR(rstack_push_rstack(rs24, rs68));
    NO_ERROR(rstack_push_rstack(rs14, rs66));
    NO_ERROR(rstack_push_rstack(rs32, rs56));
    ASSERT_RESULT(rstack_front(rs33), false, 0UL);
    ASSERT(rstack_empty(rs55) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs58, rs7));
    NO_ERROR(rstack_push_rstack(rs23, rs64));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    ASSERT_RESULT(rstack_front(rs22), false, 0UL);
    ASSERT_RESULT(rstack_front(rs74), false, 0UL);
    ASSERT_RESULT(rstack_front(rs13), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs53, rs74));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs16, rs37));
    ASSERT_RESULT(rstack_front(rs59), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs38, rs4));
    ASSERT_RESULT(rstack_front(rs69), false, 0UL);
    ASSERT_RESULT(rstack_front(rs54), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs60));
    NO_ERROR(rstack_push_rstack(rs20, rs65));
    ASSERT(rstack_empty(rs29) == true);
    NO_ERROR(rstack_push_rstack(rs10, rs27));
    NO_ERROR(rstack_push_rstack(rs28, rs62));
    NO_ERROR(rstack_push_rstack(rs74, rs64));
    NO_ERROR(rstack_push_rstack(rs29, rs64));
    NO_ERROR(rstack_push_rstack(rs72, rs1));
    NO_ERROR(rstack_push_rstack(rs53, rs36));
    NO_ERROR(rstack_push_rstack(rs63, rs47));
    NO_ERROR(rstack_push_rstack(rs43, rs51));
    NO_ERROR(rstack_push_rstack(rs32, rs64));
    NO_ERROR(rstack_push_rstack(rs36, rs27));
    NO_ERROR(rstack_push_rstack(rs32, rs38));
    ASSERT(rstack_empty(rs35) == true);
    NO_ERROR(rstack_push_rstack(rs24, rs20));
    NO_ERROR(rstack_push_rstack(rs24, rs12));
    NO_ERROR(rstack_push_rstack(rs28, rs47));
    rstack_delete(rs70);
    rstack_delete(rs71);
    rstack_delete(rs72);
    rstack_delete(rs73);
    rstack_delete(rs74);
    NO_ERROR(rstack_push_rstack(rs30, rs5));
    NO_ERROR(rstack_push_rstack(rs64, rs44));
    ASSERT_RESULT(rstack_front(rs26), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs39, rs59));
    NO_ERROR(rstack_push_rstack(rs7, rs56));
    NO_ERROR(rstack_push_rstack(rs10, rs68));
    ASSERT_RESULT(rstack_front(rs59), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs51, rs32));
    ASSERT_RESULT(rstack_front(rs53), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs59));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT(rstack_empty(rs45) == true);
    NO_ERROR(rstack_push_rstack(rs69, rs5));
    NO_ERROR(rstack_push_rstack(rs49, rs42));
    NO_ERROR(rstack_push_rstack(rs28, rs52));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs12, rs68));
    NO_ERROR(rstack_push_rstack(rs37, rs59));
    ASSERT(rstack_empty(rs62) == true);
    NO_ERROR(rstack_push_rstack(rs37, rs30));
    NO_ERROR(rstack_push_rstack(rs61, rs58));
    NO_ERROR(rstack_push_rstack(rs57, rs34));
    ASSERT(rstack_empty(rs69) == true);
    NO_ERROR(rstack_push_rstack(rs30, rs18));
    NO_ERROR(rstack_push_rstack(rs4, rs11));
    NO_ERROR(rstack_push_rstack(rs3, rs49));
    NO_ERROR(rstack_push_rstack(rs64, rs7));
    NO_ERROR(rstack_push_rstack(rs36, rs35));
    NO_ERROR(rstack_push_rstack(rs14, rs24));
    NO_ERROR(rstack_push_rstack(rs40, rs57));
    ASSERT_RESULT(rstack_front(rs27), false, 0UL);
    ASSERT_RESULT(rstack_front(rs49), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs17, rs14));
    NO_ERROR(rstack_push_rstack(rs25, rs45));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    ASSERT_RESULT(rstack_front(rs37), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs49, rs52));
    ASSERT(rstack_empty(rs35) == true);
    rstack_delete(rs65);
    rstack_delete(rs66);
    rstack_delete(rs67);
    rstack_delete(rs68);
    rstack_delete(rs69);
    ASSERT_RESULT(rstack_front(rs51), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs59, rs46));
    NO_ERROR(rstack_push_rstack(rs47, rs52));
    NO_ERROR(rstack_push_rstack(rs43, rs52));
    NO_ERROR(rstack_push_rstack(rs27, rs54));
    NO_ERROR(rstack_push_rstack(rs4, rs32));
    NO_ERROR(rstack_push_rstack(rs41, rs40));
    NO_ERROR(rstack_push_rstack(rs30, rs56));
    ASSERT(rstack_empty(rs5) == true);
    NO_ERROR(rstack_push_rstack(rs49, rs38));
    ASSERT_RESULT(rstack_front(rs28), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs50));
    NO_ERROR(rstack_push_rstack(rs1, rs63));
    NO_ERROR(rstack_push_rstack(rs0, rs47));
    NO_ERROR(rstack_push_rstack(rs16, rs48));
    ASSERT_RESULT(rstack_front(rs42), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs10, rs1));
    NO_ERROR(rstack_push_rstack(rs56, rs46));
    NO_ERROR(rstack_push_rstack(rs63, rs14));
    ASSERT(rstack_empty(rs35) == true);
    NO_ERROR(rstack_push_rstack(rs42, rs37));
    ASSERT_RESULT(rstack_front(rs64), false, 0UL);
    ASSERT_RESULT(rstack_front(rs21), false, 0UL);
    ASSERT(rstack_empty(rs26) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs40));
    ASSERT_RESULT(rstack_front(rs52), false, 0UL);
    ASSERT_RESULT(rstack_front(rs56), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs50, rs19));
    NO_ERROR(rstack_push_rstack(rs40, rs46));
    NO_ERROR(rstack_push_rstack(rs38, rs63));
    NO_ERROR(rstack_push_rstack(rs40, rs37));
    ASSERT_RESULT(rstack_front(rs62), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs28, rs27));
    NO_ERROR(rstack_push_rstack(rs53, rs5));
    NO_ERROR(rstack_push_rstack(rs47, rs9));
    ASSERT_RESULT(rstack_front(rs41), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs47, rs18));
    ASSERT_RESULT(rstack_front(rs32), false, 0UL);
    rstack_delete(rs60);
    rstack_delete(rs61);
    rstack_delete(rs62);
    rstack_delete(rs63);
    rstack_delete(rs64);
    NO_ERROR(rstack_push_rstack(rs43, rs36));
    NO_ERROR(rstack_push_rstack(rs53, rs43));
    NO_ERROR(rstack_push_rstack(rs7, rs21));
    ASSERT_RESULT(rstack_front(rs38), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs55, rs22));
    NO_ERROR(rstack_push_rstack(rs6, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT(rstack_empty(rs16) == true);
    NO_ERROR(rstack_push_rstack(rs39, rs24));
    ASSERT_RESULT(rstack_front(rs28), false, 0UL);
    ASSERT_RESULT(rstack_front(rs38), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs11, rs56));
    NO_ERROR(rstack_push_rstack(rs15, rs29));
    NO_ERROR(rstack_push_rstack(rs37, rs48));
    NO_ERROR(rstack_push_rstack(rs40, rs16));
    NO_ERROR(rstack_push_rstack(rs31, rs27));
    NO_ERROR(rstack_push_rstack(rs22, rs37));
    NO_ERROR(rstack_push_rstack(rs34, rs59));
    ASSERT_RESULT(rstack_front(rs24), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs48, rs29));
    ASSERT(rstack_empty(rs23) == true);
    ASSERT(rstack_empty(rs36) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs40));
    ASSERT_RESULT(rstack_front(rs51), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs10, rs58));
    NO_ERROR(rstack_push_rstack(rs18, rs9));
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs20, rs45));
    ASSERT_RESULT(rstack_front(rs26), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs59, rs25));
    NO_ERROR(rstack_push_rstack(rs21, rs23));
    NO_ERROR(rstack_push_rstack(rs52, rs14));
    NO_ERROR(rstack_push_rstack(rs48, rs5));
    NO_ERROR(rstack_push_rstack(rs37, rs19));
    NO_ERROR(rstack_push_rstack(rs43, rs9));
    ASSERT(rstack_empty(rs34) == true);
    ASSERT(rstack_empty(rs20) == true);
    rstack_delete(rs55);
    rstack_delete(rs56);
    rstack_delete(rs57);
    rstack_delete(rs58);
    rstack_delete(rs59);
    NO_ERROR(rstack_push_rstack(rs47, rs47));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs28), false, 0UL);
    ASSERT(rstack_empty(rs41) == true);
    ASSERT_RESULT(rstack_front(rs37), false, 0UL);
    ASSERT_RESULT(rstack_front(rs54), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs21));
    NO_ERROR(rstack_push_rstack(rs36, rs15));
    NO_ERROR(rstack_push_rstack(rs14, rs35));
    NO_ERROR(rstack_push_rstack(rs45, rs51));
    NO_ERROR(rstack_push_rstack(rs49, rs39));
    ASSERT_RESULT(rstack_front(rs33), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs30, rs11));
    ASSERT_RESULT(rstack_front(rs13), false, 0UL);
    ASSERT_RESULT(rstack_front(rs41), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs7));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    ASSERT(rstack_empty(rs45) == true);
    NO_ERROR(rstack_push_rstack(rs45, rs44));
    NO_ERROR(rstack_push_rstack(rs42, rs43));
    NO_ERROR(rstack_push_rstack(rs21, rs37));
    NO_ERROR(rstack_push_rstack(rs25, rs34));
    NO_ERROR(rstack_push_rstack(rs30, rs11));
    ASSERT(rstack_empty(rs5) == true);
    NO_ERROR(rstack_push_rstack(rs8, rs41));
    NO_ERROR(rstack_push_rstack(rs53, rs40));
    NO_ERROR(rstack_push_rstack(rs24, rs18));
    ASSERT(rstack_empty(rs51) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs12));
    NO_ERROR(rstack_push_rstack(rs36, rs52));
    NO_ERROR(rstack_push_rstack(rs35, rs33));
    NO_ERROR(rstack_push_rstack(rs19, rs34));
    ASSERT_RESULT(rstack_front(rs42), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs40, rs5));
    NO_ERROR(rstack_push_rstack(rs13, rs5));
    NO_ERROR(rstack_push_rstack(rs25, rs9));
    rstack_delete(rs50);
    rstack_delete(rs51);
    rstack_delete(rs52);
    rstack_delete(rs53);
    rstack_delete(rs54);
    NO_ERROR(rstack_push_rstack(rs19, rs47));
    NO_ERROR(rstack_push_rstack(rs5, rs48));
    ASSERT(rstack_empty(rs15) == true);
    NO_ERROR(rstack_push_rstack(rs23, rs18));
    NO_ERROR(rstack_push_rstack(rs28, rs30));
    NO_ERROR(rstack_push_rstack(rs13, rs34));
    NO_ERROR(rstack_push_rstack(rs38, rs19));
    NO_ERROR(rstack_push_rstack(rs8, rs39));
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    ASSERT(rstack_empty(rs34) == true);
    ASSERT(rstack_empty(rs48) == true);
    NO_ERROR(rstack_push_rstack(rs47, rs5));
    ASSERT(rstack_empty(rs9) == true);
    NO_ERROR(rstack_push_rstack(rs40, rs12));
    NO_ERROR(rstack_push_rstack(rs35, rs32));
    ASSERT_RESULT(rstack_front(rs38), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs25, rs31));
    NO_ERROR(rstack_push_rstack(rs36, rs1));
    NO_ERROR(rstack_push_rstack(rs27, rs0));
    NO_ERROR(rstack_push_rstack(rs10, rs34));
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs40, rs35));
    NO_ERROR(rstack_push_rstack(rs30, rs24));
    NO_ERROR(rstack_push_rstack(rs30, rs43));
    NO_ERROR(rstack_push_rstack(rs28, rs40));
    NO_ERROR(rstack_push_rstack(rs22, rs46));
    ASSERT(rstack_empty(rs42) == true);
    NO_ERROR(rstack_push_rstack(rs49, rs40));
    ASSERT_RESULT(rstack_front(rs20), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs32, rs6));
    NO_ERROR(rstack_push_rstack(rs35, rs21));
    NO_ERROR(rstack_push_rstack(rs6, rs34));
    ASSERT_RESULT(rstack_front(rs40), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs17));
    NO_ERROR(rstack_push_rstack(rs10, rs45));
    ASSERT_RESULT(rstack_front(rs24), false, 0UL);
    rstack_delete(rs45);
    rstack_delete(rs46);
    rstack_delete(rs47);
    rstack_delete(rs48);
    rstack_delete(rs49);
    NO_ERROR(rstack_push_rstack(rs4, rs7));
    NO_ERROR(rstack_push_rstack(rs27, rs21));
    NO_ERROR(rstack_push_rstack(rs13, rs34));
    ASSERT(rstack_empty(rs31) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs30));
    ASSERT(rstack_empty(rs13) == true);
    ASSERT_RESULT(rstack_front(rs22), false, 0UL);
    ASSERT_RESULT(rstack_front(rs27), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs14, rs26));
    NO_ERROR(rstack_push_rstack(rs30, rs23));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs42));
    NO_ERROR(rstack_push_rstack(rs28, rs39));
    ASSERT_RESULT(rstack_front(rs28), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs26, rs8));
    NO_ERROR(rstack_push_rstack(rs12, rs4));
    NO_ERROR(rstack_push_rstack(rs29, rs38));
    NO_ERROR(rstack_push_rstack(rs10, rs28));
    NO_ERROR(rstack_push_rstack(rs10, rs19));
    ASSERT_RESULT(rstack_front(rs25), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs28));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    ASSERT(rstack_empty(rs12) == true);
    NO_ERROR(rstack_push_rstack(rs15, rs30));
    NO_ERROR(rstack_push_rstack(rs41, rs41));
    NO_ERROR(rstack_push_rstack(rs7, rs3));
    NO_ERROR(rstack_push_rstack(rs43, rs11));
    NO_ERROR(rstack_push_rstack(rs36, rs26));
    NO_ERROR(rstack_push_rstack(rs40, rs20));
    NO_ERROR(rstack_push_rstack(rs1, rs6));
    NO_ERROR(rstack_push_rstack(rs31, rs29));
    NO_ERROR(rstack_push_rstack(rs30, rs35));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    ASSERT(rstack_empty(rs44) == true);
    NO_ERROR(rstack_push_rstack(rs43, rs33));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs26, rs43));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    rstack_delete(rs40);
    rstack_delete(rs41);
    rstack_delete(rs42);
    rstack_delete(rs43);
    rstack_delete(rs44);
    NO_ERROR(rstack_push_rstack(rs3, rs22));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs25));
    NO_ERROR(rstack_push_rstack(rs9, rs25));
    NO_ERROR(rstack_push_rstack(rs19, rs0));
    ASSERT(rstack_empty(rs34) == true);
    NO_ERROR(rstack_push_rstack(rs6, rs39));
    ASSERT_RESULT(rstack_front(rs36), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs36, rs11));
    NO_ERROR(rstack_push_rstack(rs4, rs16));
    NO_ERROR(rstack_push_rstack(rs37, rs38));
    NO_ERROR(rstack_push_rstack(rs21, rs11));
    NO_ERROR(rstack_push_rstack(rs1, rs36));
    NO_ERROR(rstack_push_rstack(rs36, rs20));
    NO_ERROR(rstack_push_rstack(rs28, rs29));
    NO_ERROR(rstack_push_rstack(rs29, rs28));
    ASSERT(rstack_empty(rs27) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs13));
    ASSERT(rstack_empty(rs18) == true);
    ASSERT(rstack_empty(rs13) == true);
    ASSERT(rstack_empty(rs31) == true);
    ASSERT(rstack_empty(rs24) == true);
    NO_ERROR(rstack_push_rstack(rs28, rs9));
    NO_ERROR(rstack_push_rstack(rs0, rs12));
    NO_ERROR(rstack_push_rstack(rs33, rs1));
    NO_ERROR(rstack_push_rstack(rs27, rs19));
    NO_ERROR(rstack_push_rstack(rs22, rs37));
    ASSERT(rstack_empty(rs14) == true);
    NO_ERROR(rstack_push_rstack(rs34, rs23));
    NO_ERROR(rstack_push_rstack(rs4, rs18));
    NO_ERROR(rstack_push_rstack(rs4, rs17));
    ASSERT(rstack_empty(rs24) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs23, rs1));
    NO_ERROR(rstack_push_rstack(rs35, rs31));
    NO_ERROR(rstack_push_rstack(rs35, rs20));
    rstack_delete(rs35);
    rstack_delete(rs36);
    rstack_delete(rs37);
    rstack_delete(rs38);
    rstack_delete(rs39);
    NO_ERROR(rstack_push_rstack(rs6, rs18));
    NO_ERROR(rstack_push_rstack(rs15, rs32));
    NO_ERROR(rstack_push_rstack(rs13, rs31));
    ASSERT(rstack_empty(rs8) == true);
    NO_ERROR(rstack_push_rstack(rs10, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs29, rs21));
    NO_ERROR(rstack_push_rstack(rs27, rs28));
    NO_ERROR(rstack_push_rstack(rs17, rs9));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs18, rs29));
    ASSERT_RESULT(rstack_front(rs21), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs30));
    ASSERT(rstack_empty(rs13) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs20));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs16, rs27));
    NO_ERROR(rstack_push_rstack(rs5, rs33));
    NO_ERROR(rstack_push_rstack(rs25, rs7));
    NO_ERROR(rstack_push_rstack(rs17, rs4));
    ASSERT_RESULT(rstack_front(rs15), false, 0UL);
    ASSERT_RESULT(rstack_front(rs26), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs23, rs15));
    NO_ERROR(rstack_push_rstack(rs9, rs28));
    NO_ERROR(rstack_push_rstack(rs22, rs14));
    NO_ERROR(rstack_push_rstack(rs10, rs22));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs30));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    ASSERT(rstack_empty(rs23) == true);
    ASSERT_RESULT(rstack_front(rs30), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs18));
    ASSERT_RESULT(rstack_front(rs26), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs14, rs30));
    NO_ERROR(rstack_push_rstack(rs9, rs31));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs21, rs9));
    NO_ERROR(rstack_push_rstack(rs12, rs13));
    rstack_delete(rs30);
    rstack_delete(rs31);
    rstack_delete(rs32);
    rstack_delete(rs33);
    rstack_delete(rs34);
    NO_ERROR(rstack_push_rstack(rs0, rs5));
    NO_ERROR(rstack_push_rstack(rs25, rs17));
    NO_ERROR(rstack_push_rstack(rs27, rs11));
    NO_ERROR(rstack_push_rstack(rs5, rs9));
    NO_ERROR(rstack_push_rstack(rs25, rs27));
    NO_ERROR(rstack_push_rstack(rs11, rs8));
    NO_ERROR(rstack_push_rstack(rs25, rs25));
    NO_ERROR(rstack_push_rstack(rs24, rs2));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs13, rs23));
    NO_ERROR(rstack_push_rstack(rs4, rs16));
    NO_ERROR(rstack_push_rstack(rs19, rs12));
    NO_ERROR(rstack_push_rstack(rs21, rs0));
    ASSERT(rstack_empty(rs1) == true);
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    ASSERT(rstack_empty(rs26) == true);
    NO_ERROR(rstack_push_rstack(rs28, rs6));
    NO_ERROR(rstack_push_rstack(rs19, rs29));
    ASSERT(rstack_empty(rs1) == true);
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    ASSERT_RESULT(rstack_front(rs14), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs24, rs21));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    ASSERT_RESULT(rstack_front(rs13), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs19, rs1));
    NO_ERROR(rstack_push_rstack(rs7, rs28));
    ASSERT(rstack_empty(rs25) == true);
    NO_ERROR(rstack_push_rstack(rs5, rs13));
    NO_ERROR(rstack_push_rstack(rs12, rs21));
    ASSERT_RESULT(rstack_front(rs14), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    NO_ERROR(rstack_push_rstack(rs4, rs13));
    NO_ERROR(rstack_push_rstack(rs6, rs19));
    NO_ERROR(rstack_push_rstack(rs7, rs3));
    ASSERT_RESULT(rstack_front(rs23), false, 0UL);
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs12, rs16));
    NO_ERROR(rstack_push_rstack(rs26, rs22));
    rstack_delete(rs25);
    rstack_delete(rs26);
    rstack_delete(rs27);
    rstack_delete(rs28);
    rstack_delete(rs29);
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs8, rs5));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs5, rs0));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs18, rs20));
    NO_ERROR(rstack_push_rstack(rs18, rs16));
    ASSERT_RESULT(rstack_front(rs14), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs24, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs19));
    NO_ERROR(rstack_push_rstack(rs23, rs15));
    ASSERT(rstack_empty(rs12) == true);
    NO_ERROR(rstack_push_rstack(rs21, rs21));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT(rstack_empty(rs22) == true);
    NO_ERROR(rstack_push_rstack(rs6, rs6));
    NO_ERROR(rstack_push_rstack(rs21, rs22));
    NO_ERROR(rstack_push_rstack(rs18, rs15));
    NO_ERROR(rstack_push_rstack(rs20, rs20));
    ASSERT(rstack_empty(rs9) == true);
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs12));
    ASSERT(rstack_empty(rs1) == true);
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs13, rs7));
    NO_ERROR(rstack_push_rstack(rs12, rs5));
    NO_ERROR(rstack_push_rstack(rs0, rs15));
    NO_ERROR(rstack_push_rstack(rs23, rs4));
    NO_ERROR(rstack_push_rstack(rs16, rs14));
    ASSERT_RESULT(rstack_front(rs23), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs8));
    ASSERT(rstack_empty(rs19) == true);
    ASSERT_RESULT(rstack_front(rs19), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs11, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs12));
    NO_ERROR(rstack_push_rstack(rs24, rs12));
    rstack_delete(rs20);
    rstack_delete(rs21);
    rstack_delete(rs22);
    rstack_delete(rs23);
    rstack_delete(rs24);
    NO_ERROR(rstack_push_rstack(rs12, rs4));
    NO_ERROR(rstack_push_rstack(rs13, rs12));
    NO_ERROR(rstack_push_rstack(rs19, rs19));
    NO_ERROR(rstack_push_rstack(rs13, rs7));
    NO_ERROR(rstack_push_rstack(rs1, rs8));
    NO_ERROR(rstack_push_rstack(rs17, rs3));
    NO_ERROR(rstack_push_rstack(rs14, rs7));
    NO_ERROR(rstack_push_rstack(rs10, rs18));
    NO_ERROR(rstack_push_rstack(rs19, rs15));
    NO_ERROR(rstack_push_rstack(rs13, rs0));
    ASSERT(rstack_empty(rs10) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs19));
    NO_ERROR(rstack_push_rstack(rs11, rs18));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs18));
    NO_ERROR(rstack_push_rstack(rs17, rs16));
    ASSERT(rstack_empty(rs15) == true);
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs1));
    NO_ERROR(rstack_push_rstack(rs14, rs8));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs11, rs8));
    NO_ERROR(rstack_push_rstack(rs7, rs6));
    NO_ERROR(rstack_push_rstack(rs18, rs11));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT_RESULT(rstack_front(rs19), false, 0UL);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT(rstack_empty(rs18) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs11));
    ASSERT(rstack_empty(rs1) == true);
    ASSERT_RESULT(rstack_front(rs17), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs9));
    NO_ERROR(rstack_push_rstack(rs15, rs17));
    NO_ERROR(rstack_push_rstack(rs1, rs10));
    NO_ERROR(rstack_push_rstack(rs2, rs10));
    ASSERT(rstack_empty(rs4) == true);
    rstack_delete(rs15);
    rstack_delete(rs16);
    rstack_delete(rs17);
    rstack_delete(rs18);
    rstack_delete(rs19);
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs13, rs7));
    NO_ERROR(rstack_push_rstack(rs2, rs13));
    NO_ERROR(rstack_push_rstack(rs4, rs12));
    NO_ERROR(rstack_push_rstack(rs9, rs8));
    NO_ERROR(rstack_push_rstack(rs5, rs11));
    NO_ERROR(rstack_push_rstack(rs9, rs13));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs6, rs6));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs12, rs4));
    NO_ERROR(rstack_push_rstack(rs9, rs7));
    NO_ERROR(rstack_push_rstack(rs0, rs13));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs7));
    NO_ERROR(rstack_push_rstack(rs14, rs12));
    ASSERT(rstack_empty(rs11) == true);
    NO_ERROR(rstack_push_rstack(rs10, rs5));
    NO_ERROR(rstack_push_rstack(rs6, rs6));
    ASSERT(rstack_empty(rs11) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs0));
    NO_ERROR(rstack_push_rstack(rs9, rs8));
    NO_ERROR(rstack_push_rstack(rs5, rs2));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    NO_ERROR(rstack_push_rstack(rs1, rs8));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs14, rs9));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    ASSERT(rstack_empty(rs7) == true);
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs13, rs8));
    NO_ERROR(rstack_push_rstack(rs1, rs6));
    NO_ERROR(rstack_push_rstack(rs6, rs4));
    rstack_delete(rs10);
    rstack_delete(rs11);
    rstack_delete(rs12);
    rstack_delete(rs13);
    rstack_delete(rs14);
    ASSERT(rstack_empty(rs5) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs6));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs5, rs7));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs8));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs8));
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs1));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs8));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    NO_ERROR(rstack_push_rstack(rs5, rs3));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs9, rs5));
    NO_ERROR(rstack_push_rstack(rs0, rs5));
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs5, rs5));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs9));
    NO_ERROR(rstack_push_rstack(rs3, rs8));
    NO_ERROR(rstack_push_rstack(rs7, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs7));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT(rstack_empty(rs4) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs6));
    rstack_delete(rs5);
    rstack_delete(rs6);
    rstack_delete(rs7);
    rstack_delete(rs8);
    rstack_delete(rs9);
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    ASSERT(rstack_empty(rs2) == true);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    rstack_delete(rs0);
    rstack_delete(rs1);
    rstack_delete(rs2);
    rstack_delete(rs3);
    rstack_delete(rs4);
        
        return PASS;
}
