#include "../macros.h"
#include "../rstack.h"
#include <assert.h>

int main(void) {
    rstack_t* rs0 = rstack_new();
    rstack_t* rs1 = rstack_new();
    rstack_t* rs2 = rstack_new();
    rstack_t* rs3 = rstack_new();
    rstack_t* rs4 = rstack_new();
    rstack_t* rs5 = rstack_new();
    rstack_t* rs6 = rstack_new();
    rstack_t* rs7 = rstack_new();
    rstack_t* rs8 = rstack_new();
    rstack_t* rs9 = rstack_new();
    NO_ERROR(rstack_write("test_3.fout", rs5));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs7));
    NO_ERROR(rstack_push_rstack(rs4, rs7));
    NO_ERROR(rstack_push_rstack(rs9, rs3));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs8));
    NO_ERROR(rstack_push_rstack(rs5, rs7));
    NO_ERROR(rstack_push_rstack(rs5, rs7));
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs7, rs8));
    NO_ERROR(rstack_push_rstack(rs4, rs5));
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    NO_ERROR(rstack_push_rstack(rs5, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    NO_ERROR(rstack_push_rstack(rs5, rs9));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs9));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    ASSERT(rstack_empty(rs6) == true);
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs9));
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    NO_ERROR(rstack_write("test_7.fout", rs6));
    NO_ERROR(rstack_push_rstack(rs5, rs6));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs4));
    NO_ERROR(rstack_push_rstack(rs8, rs8));
    NO_ERROR(rstack_push_rstack(rs7, rs6));
    NO_ERROR(rstack_push_rstack(rs8, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs7));
    ASSERT(rstack_empty(rs5) == true);
    ASSERT(rstack_empty(rs6) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs3));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    NO_ERROR(rstack_push_rstack(rs8, rs8));
    NO_ERROR(rstack_push_rstack(rs3, rs8));
    NO_ERROR(rstack_push_rstack(rs4, rs5));
    NO_ERROR(rstack_push_rstack(rs7, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs8));
    NO_ERROR(rstack_push_rstack(rs7, rs8));
    ASSERT(rstack_empty(rs9) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs9));
    NO_ERROR(rstack_push_rstack(rs1, rs7));
    NO_ERROR(rstack_push_rstack(rs3, rs6));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs4));
    ASSERT(rstack_empty(rs1) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs6));
    NO_ERROR(rstack_push_rstack(rs6, rs1));
    NO_ERROR(rstack_push_rstack(rs9, rs2));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs9));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    NO_ERROR(rstack_push_rstack(rs6, rs2));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs8));
    ASSERT(rstack_empty(rs5) == true);
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs5, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    ASSERT(rstack_empty(rs3) == true);
    ASSERT(rstack_empty(rs8) == true);
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs7));
    NO_ERROR(rstack_push_rstack(rs8, rs1));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs0));
    NO_ERROR(rstack_push_rstack(rs9, rs7));
    NO_ERROR(rstack_push_rstack(rs7, rs4));
    ASSERT(rstack_empty(rs5) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    NO_ERROR(rstack_push_rstack(rs7, rs3));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs8));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT(rstack_empty(rs8) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    NO_ERROR(rstack_push_rstack(rs5, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs5));
    NO_ERROR(rstack_push_rstack(rs6, rs3));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs7));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs6));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs9, rs5));
    NO_ERROR(rstack_push_rstack(rs2, rs6));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_write("test_1.fout", rs8));
    NO_ERROR(rstack_push_rstack(rs9, rs7));
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_write("test_4.fout", rs7));
    NO_ERROR(rstack_push_rstack(rs1, rs6));
    NO_ERROR(rstack_push_rstack(rs0, rs5));
    ASSERT(rstack_empty(rs6) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs6));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    NO_ERROR(rstack_push_rstack(rs2, rs8));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs9, rs9));
    NO_ERROR(rstack_push_rstack(rs8, rs2));
    NO_ERROR(rstack_push_rstack(rs7, rs3));
    ASSERT(rstack_empty(rs5) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs4, rs7));
    ASSERT(rstack_empty(rs6) == true);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_write("test_9.fout", rs8));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs8, rs9));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs5, rs5));
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs8));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs9, rs3));
    NO_ERROR(rstack_push_rstack(rs6, rs8));
    NO_ERROR(rstack_push_rstack(rs5, rs4));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs2));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs6, rs6));
    NO_ERROR(rstack_push_rstack(rs7, rs1));
    NO_ERROR(rstack_push_rstack(rs7, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs8));
    NO_ERROR(rstack_push_rstack(rs9, rs6));
    NO_ERROR(rstack_push_rstack(rs5, rs6));
    NO_ERROR(rstack_push_rstack(rs7, rs9));
    NO_ERROR(rstack_push_rstack(rs2, rs8));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs8));
    NO_ERROR(rstack_push_rstack(rs1, rs6));
    NO_ERROR(rstack_push_rstack(rs3, rs6));
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    NO_ERROR(rstack_push_rstack(rs2, rs6));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs8, rs9));
    NO_ERROR(rstack_push_rstack(rs9, rs1));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    ASSERT(rstack_empty(rs7) == true);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs9));
    NO_ERROR(rstack_push_rstack(rs0, rs9));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs6));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs6, rs5));
    NO_ERROR(rstack_push_rstack(rs7, rs6));
    NO_ERROR(rstack_push_rstack(rs6, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs6, rs1));
    NO_ERROR(rstack_push_rstack(rs8, rs8));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs3));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs6, rs8));
    NO_ERROR(rstack_push_rstack(rs8, rs2));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs8));
    NO_ERROR(rstack_push_rstack(rs4, rs6));
    ASSERT(rstack_empty(rs9) == true);
    NO_ERROR(rstack_push_rstack(rs9, rs2));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs7));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs9));
    NO_ERROR(rstack_push_rstack(rs2, rs7));
    NO_ERROR(rstack_push_rstack(rs1, rs5));
    NO_ERROR(rstack_push_rstack(rs8, rs8));
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_write("test_5.fout", rs7));
    ASSERT(rstack_empty(rs9) == true);
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs5));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    NO_ERROR(rstack_push_rstack(rs9, rs8));
    NO_ERROR(rstack_push_rstack(rs9, rs3));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs6));
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs8));
    ASSERT(rstack_empty(rs6) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs7));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs5));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs9));
    NO_ERROR(rstack_push_rstack(rs7, rs0));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs8));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs8));
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs4));
    NO_ERROR(rstack_push_rstack(rs8, rs7));
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs5));
    NO_ERROR(rstack_push_rstack(rs6, rs2));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs9));
    NO_ERROR(rstack_push_rstack(rs0, rs7));
    NO_ERROR(rstack_push_rstack(rs6, rs8));
    NO_ERROR(rstack_push_rstack(rs6, rs7));
    NO_ERROR(rstack_push_rstack(rs0, rs9));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs6, rs1));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs6));
    NO_ERROR(rstack_push_rstack(rs7, rs1));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs5));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    ASSERT(rstack_empty(rs8) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs7));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs6));
    NO_ERROR(rstack_push_rstack(rs6, rs9));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_write("test_2.fout", rs5));
    NO_ERROR(rstack_push_rstack(rs8, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs5));
    NO_ERROR(rstack_push_rstack(rs0, rs7));
    NO_ERROR(rstack_push_rstack(rs1, rs8));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs5));
    NO_ERROR(rstack_push_rstack(rs8, rs5));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs8));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs8, rs8));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs7));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs8));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs8, rs0));
    NO_ERROR(rstack_push_rstack(rs6, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs5));
    NO_ERROR(rstack_push_rstack(rs6, rs3));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT(rstack_empty(rs8) == true);
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs9, rs6));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_write("test_0.fout", rs5));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs7));
    NO_ERROR(rstack_push_rstack(rs9, rs4));
    ASSERT(rstack_empty(rs0) == true);
    ASSERT(rstack_empty(rs4) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs7, rs0));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_write("test_6.fout", rs0));
    NO_ERROR(rstack_push_rstack(rs9, rs0));
    NO_ERROR(rstack_push_rstack(rs7, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs5));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs8));
    NO_ERROR(rstack_push_rstack(rs9, rs5));
    NO_ERROR(rstack_push_rstack(rs6, rs9));
    NO_ERROR(rstack_push_rstack(rs1, rs8));
    NO_ERROR(rstack_push_rstack(rs9, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs7));
    NO_ERROR(rstack_write("test_8.fout", rs2));
    ASSERT(rstack_empty(rs8) == true);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs2));
    NO_ERROR(rstack_push_rstack(rs7, rs4));
    ASSERT(rstack_empty(rs6) == true);
    NO_ERROR(rstack_push_rstack(rs9, rs8));
    NO_ERROR(rstack_push_rstack(rs5, rs3));
    ASSERT(rstack_empty(rs9) == true);
    NO_ERROR(rstack_push_rstack(rs6, rs3));
    NO_ERROR(rstack_push_rstack(rs9, rs5));
    NO_ERROR(rstack_push_rstack(rs8, rs3));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs8));
    NO_ERROR(rstack_push_rstack(rs1, rs6));
    NO_ERROR(rstack_push_rstack(rs5, rs2));
    NO_ERROR(rstack_push_rstack(rs8, rs1));
    NO_ERROR(rstack_push_rstack(rs8, rs9));
    NO_ERROR(rstack_push_rstack(rs0, rs7));
    NO_ERROR(rstack_push_rstack(rs1, rs7));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs4));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs7, rs6));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    NO_ERROR(rstack_push_rstack(rs3, rs9));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs9));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs5));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs6, rs8));
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs5));
    NO_ERROR(rstack_push_rstack(rs4, rs8));
    ASSERT(rstack_empty(rs7) == true);
    NO_ERROR(rstack_push_rstack(rs7, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs9));
    ASSERT(rstack_empty(rs9) == true);
    NO_ERROR(rstack_push_rstack(rs5, rs8));
    NO_ERROR(rstack_push_rstack(rs0, rs8));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    rstack_delete(rs5);
    rstack_delete(rs6);
    rstack_delete(rs7);
    rstack_delete(rs8);
    rstack_delete(rs9);
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    ASSERT(rstack_empty(rs4) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT(rstack_empty(rs4) == true);
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT(rstack_empty(rs1) == true);
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    ASSERT(rstack_empty(rs3) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT(rstack_empty(rs4) == true);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs2));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    ASSERT(rstack_empty(rs4) == true);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT(rstack_empty(rs4) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    ASSERT(rstack_empty(rs0) == true);
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    ASSERT(rstack_empty(rs2) == true);
    ASSERT(rstack_empty(rs4) == true);
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT(rstack_empty(rs2) == true);
    ASSERT(rstack_empty(rs3) == true);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT(rstack_empty(rs3) == true);
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    ASSERT(rstack_empty(rs2) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs1, rs0));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT(rstack_empty(rs1) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    ASSERT(rstack_empty(rs2) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs0));
    NO_ERROR(rstack_push_rstack(rs1, rs1));
    NO_ERROR(rstack_push_rstack(rs4, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs2));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs1));
    NO_ERROR(rstack_push_rstack(rs2, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs0));
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs3, rs4));
    ASSERT(rstack_empty(rs0) == true);
    ASSERT_RESULT(rstack_front(rs0), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs4));
    NO_ERROR(rstack_push_rstack(rs2, rs1));
    ASSERT(rstack_empty(rs4) == true);
    NO_ERROR(rstack_push_rstack(rs1, rs4));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs2));
    ASSERT(rstack_empty(rs0) == true);
    ASSERT(rstack_empty(rs0) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    ASSERT_RESULT(rstack_front(rs3), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs0));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs2));
    NO_ERROR(rstack_push_rstack(rs4, rs1));
    NO_ERROR(rstack_push_rstack(rs4, rs3));
    NO_ERROR(rstack_push_rstack(rs3, rs0));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    ASSERT(rstack_empty(rs4) == true);
    ASSERT(rstack_empty(rs3) == true);
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs3, rs3));
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs3));
    ASSERT(rstack_empty(rs3) == true);
    rstack_delete(rs0);
    rstack_delete(rs1);
    rstack_delete(rs2);
    rstack_delete(rs3);
    rstack_delete(rs4);
        
        return PASS;
}
