#include "../macros.h"
#include "../rstack.h"
#include <assert.h>

int main(void) {
    rstack_t* rs0 = rstack_new();
    rstack_t* rs1 = rstack_new();
    rstack_t* rs2 = rstack_new();
    rstack_t* rs3 = rstack_new();
    rstack_t* rs4 = rstack_new();
    rstack_t* rs5 = rstack_new();
    rstack_t* rs6 = rstack_new();
    rstack_t* rs7 = rstack_new();
    rstack_t* rs8 = rstack_new();
    rstack_t* rs9 = rstack_new();
    rstack_t* rs10 = rstack_new();
    rstack_t* rs11 = rstack_new();
    rstack_t* rs12 = rstack_new();
    rstack_t* rs13 = rstack_new();
    rstack_t* rs14 = rstack_new();
    rstack_t* rs15 = rstack_new();
    rstack_t* rs16 = rstack_new();
    rstack_t* rs17 = rstack_new();
    rstack_t* rs18 = rstack_new();
    rstack_t* rs19 = rstack_new();
    rstack_t* rs20 = rstack_new();
    rstack_t* rs21 = rstack_new();
    rstack_t* rs22 = rstack_new();
    rstack_t* rs23 = rstack_new();
    rstack_t* rs24 = rstack_new();
    rstack_t* rs25 = rstack_new();
    rstack_t* rs26 = rstack_new();
    rstack_t* rs27 = rstack_new();
    rstack_t* rs28 = rstack_new();
    rstack_t* rs29 = rstack_new();
    rstack_t* rs30 = rstack_new();
    rstack_t* rs31 = rstack_new();
    rstack_t* rs32 = rstack_new();
    rstack_t* rs33 = rstack_new();
    rstack_t* rs34 = rstack_new();
    rstack_t* rs35 = rstack_new();
    rstack_t* rs36 = rstack_new();
    rstack_t* rs37 = rstack_new();
    rstack_t* rs38 = rstack_new();
    rstack_t* rs39 = rstack_new();
    rstack_t* rs40 = rstack_new();
    rstack_t* rs41 = rstack_new();
    rstack_t* rs42 = rstack_new();
    rstack_t* rs43 = rstack_new();
    rstack_t* rs44 = rstack_new();
    rstack_t* rs45 = rstack_new();
    rstack_t* rs46 = rstack_new();
    rstack_t* rs47 = rstack_new();
    rstack_t* rs48 = rstack_new();
    rstack_t* rs49 = rstack_new();
    rstack_t* rs50 = rstack_new();
    rstack_t* rs51 = rstack_new();
    rstack_t* rs52 = rstack_new();
    rstack_t* rs53 = rstack_new();
    rstack_t* rs54 = rstack_new();
    rstack_t* rs55 = rstack_new();
    rstack_t* rs56 = rstack_new();
    rstack_t* rs57 = rstack_new();
    rstack_t* rs58 = rstack_new();
    rstack_t* rs59 = rstack_new();
    rstack_t* rs60 = rstack_new();
    rstack_t* rs61 = rstack_new();
    rstack_t* rs62 = rstack_new();
    rstack_t* rs63 = rstack_new();
    rstack_t* rs64 = rstack_new();
    rstack_t* rs65 = rstack_new();
    rstack_t* rs66 = rstack_new();
    rstack_t* rs67 = rstack_new();
    rstack_t* rs68 = rstack_new();
    rstack_t* rs69 = rstack_new();
    rstack_t* rs70 = rstack_new();
    rstack_t* rs71 = rstack_new();
    rstack_t* rs72 = rstack_new();
    rstack_t* rs73 = rstack_new();
    rstack_t* rs74 = rstack_new();
    rstack_t* rs75 = rstack_new();
    rstack_t* rs76 = rstack_new();
    rstack_t* rs77 = rstack_new();
    rstack_t* rs78 = rstack_new();
    rstack_t* rs79 = rstack_new();
    rstack_t* rs80 = rstack_new();
    rstack_t* rs81 = rstack_new();
    rstack_t* rs82 = rstack_new();
    rstack_t* rs83 = rstack_new();
    rstack_t* rs84 = rstack_new();
    rstack_t* rs85 = rstack_new();
    rstack_t* rs86 = rstack_new();
    rstack_t* rs87 = rstack_new();
    rstack_t* rs88 = rstack_new();
    rstack_t* rs89 = rstack_new();
    rstack_t* rs90 = rstack_new();
    rstack_t* rs91 = rstack_new();
    rstack_t* rs92 = rstack_new();
    rstack_t* rs93 = rstack_new();
    rstack_t* rs94 = rstack_new();
    rstack_t* rs95 = rstack_new();
    rstack_t* rs96 = rstack_new();
    rstack_t* rs97 = rstack_new();
    rstack_t* rs98 = rstack_new();
    rstack_t* rs99 = rstack_new();
    ASSERT_RESULT(rstack_front(rs66), false, 0UL);
    NO_ERROR(rstack_write("test_9.fout", rs62));
    ASSERT_RESULT(rstack_front(rs23), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs61, rs45));
    NO_ERROR(rstack_push_rstack(rs28, rs1));
    ASSERT_RESULT(rstack_front(rs66), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs33));
    NO_ERROR(rstack_push_rstack(rs28, rs85));
    NO_ERROR(rstack_push_rstack(rs40, rs95));
    NO_ERROR(rstack_push_rstack(rs49, rs99));
    ASSERT(rstack_empty(rs86) == true);
    ASSERT_RESULT(rstack_front(rs99), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs42, rs5));
    NO_ERROR(rstack_push_rstack(rs4, rs86));
    NO_ERROR(rstack_push_rstack(rs64, rs22));
    NO_ERROR(rstack_push_rstack(rs24, rs79));
    NO_ERROR(rstack_push_rstack(rs88, rs64));
    ASSERT(rstack_empty(rs14) == true);
    NO_ERROR(rstack_push_rstack(rs36, rs30));
    ASSERT_RESULT(rstack_front(rs31), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs51, rs94));
    NO_ERROR(rstack_push_rstack(rs79, rs5));
    NO_ERROR(rstack_write("test_1.fout", rs89));
    ASSERT_RESULT(rstack_front(rs53), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs41, rs25));
    NO_ERROR(rstack_push_rstack(rs82, rs95));
    NO_ERROR(rstack_push_rstack(rs18, rs78));
    NO_ERROR(rstack_push_rstack(rs21, rs33));
    NO_ERROR(rstack_push_rstack(rs78, rs68));
    NO_ERROR(rstack_write("test_176.fout", rs69));
    ASSERT(rstack_empty(rs82) == true);
    NO_ERROR(rstack_push_rstack(rs41, rs69));
    ASSERT_RESULT(rstack_front(rs41), false, 0UL);
    ASSERT_RESULT(rstack_front(rs40), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs38, rs30));
    NO_ERROR(rstack_write("test_14.fout", rs9));
    NO_ERROR(rstack_write("test_98.fout", rs27));
    NO_ERROR(rstack_push_rstack(rs20, rs45));
    NO_ERROR(rstack_push_rstack(rs22, rs51));
    NO_ERROR(rstack_push_rstack(rs80, rs82));
    ASSERT(rstack_empty(rs74) == true);
    NO_ERROR(rstack_push_rstack(rs36, rs85));
    ASSERT_RESULT(rstack_front(rs20), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs71, rs65));
    NO_ERROR(rstack_push_rstack(rs32, rs33));
    ASSERT_RESULT(rstack_front(rs95), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs63, rs26));
    NO_ERROR(rstack_push_rstack(rs0, rs39));
    NO_ERROR(rstack_push_rstack(rs6, rs58));
    NO_ERROR(rstack_write("test_136.fout", rs59));
    NO_ERROR(rstack_push_rstack(rs56, rs25));
    NO_ERROR(rstack_push_rstack(rs94, rs8));
    NO_ERROR(rstack_push_rstack(rs6, rs12));
    ASSERT(rstack_empty(rs56) == true);
    ASSERT_RESULT(rstack_front(rs36), false, 0UL);
    NO_ERROR(rstack_write("test_170.fout", rs1));
    NO_ERROR(rstack_push_rstack(rs75, rs98));
    NO_ERROR(rstack_push_rstack(rs61, rs24));
    NO_ERROR(rstack_write("test_57.fout", rs29));
    NO_ERROR(rstack_push_rstack(rs56, rs44));
    NO_ERROR(rstack_push_rstack(rs26, rs77));
    ASSERT(rstack_empty(rs92) == true);
    NO_ERROR(rstack_push_rstack(rs30, rs93));
    NO_ERROR(rstack_write("test_32.fout", rs38));
    NO_ERROR(rstack_push_rstack(rs75, rs15));
    NO_ERROR(rstack_push_rstack(rs70, rs33));
    NO_ERROR(rstack_write("test_148.fout", rs5));
    ASSERT_RESULT(rstack_front(rs15), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs72, rs53));
    NO_ERROR(rstack_write("test_137.fout", rs43));
    ASSERT_RESULT(rstack_front(rs29), false, 0UL);
    ASSERT_RESULT(rstack_front(rs82), false, 0UL);
    ASSERT_RESULT(rstack_front(rs54), false, 0UL);
    NO_ERROR(rstack_write("test_142.fout", rs48));
    NO_ERROR(rstack_push_rstack(rs61, rs72));
    NO_ERROR(rstack_push_rstack(rs87, rs61));
    NO_ERROR(rstack_write("test_162.fout", rs37));
    NO_ERROR(rstack_push_rstack(rs36, rs48));
    NO_ERROR(rstack_write("test_54.fout", rs25));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs70, rs68));
    NO_ERROR(rstack_write("test_138.fout", rs49));
    NO_ERROR(rstack_write("test_8.fout", rs81));
    ASSERT_RESULT(rstack_front(rs61), false, 0UL);
    NO_ERROR(rstack_write("test_44.fout", rs43));
    ASSERT(rstack_empty(rs87) == true);
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs36, rs47));
    NO_ERROR(rstack_write("test_61.fout", rs7));
    NO_ERROR(rstack_write("test_11.fout", rs64));
    NO_ERROR(rstack_push_rstack(rs1, rs61));
    NO_ERROR(rstack_write("test_23.fout", rs6));
    NO_ERROR(rstack_push_rstack(rs73, rs57));
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    ASSERT_RESULT(rstack_front(rs53), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs37, rs81));
    NO_ERROR(rstack_push_rstack(rs10, rs35));
    NO_ERROR(rstack_write("test_114.fout", rs8));
    ASSERT_RESULT(rstack_front(rs99), false, 0UL);
    ASSERT_RESULT(rstack_front(rs61), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs87, rs81));
    NO_ERROR(rstack_push_rstack(rs30, rs24));
    NO_ERROR(rstack_push_rstack(rs15, rs77));
    NO_ERROR(rstack_write("test_62.fout", rs84));
    NO_ERROR(rstack_push_rstack(rs74, rs60));
    NO_ERROR(rstack_push_rstack(rs7, rs28));
    NO_ERROR(rstack_push_rstack(rs81, rs48));
    ASSERT_RESULT(rstack_front(rs59), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs24, rs78));
    NO_ERROR(rstack_push_rstack(rs97, rs30));
    ASSERT(rstack_empty(rs11) == true);
    ASSERT_RESULT(rstack_front(rs72), false, 0UL);
    ASSERT_RESULT(rstack_front(rs35), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs33, rs7));
    ASSERT_RESULT(rstack_front(rs32), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs44, rs39));
    NO_ERROR(rstack_push_rstack(rs57, rs93));
    NO_ERROR(rstack_write("test_26.fout", rs47));
    NO_ERROR(rstack_push_rstack(rs89, rs53));
    NO_ERROR(rstack_push_rstack(rs74, rs45));
    NO_ERROR(rstack_write("test_97.fout", rs24));
    NO_ERROR(rstack_write("test_66.fout", rs80));
    ASSERT_RESULT(rstack_front(rs51), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs77, rs59));
    NO_ERROR(rstack_push_rstack(rs63, rs94));
    NO_ERROR(rstack_write("test_77.fout", rs55));
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs1, rs77));
    NO_ERROR(rstack_write("test_19.fout", rs57));
    NO_ERROR(rstack_push_rstack(rs79, rs11));
    NO_ERROR(rstack_write("test_160.fout", rs44));
    NO_ERROR(rstack_push_rstack(rs1, rs26));
    NO_ERROR(rstack_push_rstack(rs9, rs9));
    ASSERT_RESULT(rstack_front(rs28), false, 0UL);
    NO_ERROR(rstack_write("test_75.fout", rs14));
    NO_ERROR(rstack_push_rstack(rs50, rs9));
    NO_ERROR(rstack_write("test_109.fout", rs8));
    NO_ERROR(rstack_push_rstack(rs39, rs12));
    NO_ERROR(rstack_write("test_199.fout", rs82));
    NO_ERROR(rstack_push_rstack(rs18, rs85));
    ASSERT(rstack_empty(rs32) == true);
    NO_ERROR(rstack_push_rstack(rs35, rs14));
    NO_ERROR(rstack_push_rstack(rs39, rs34));
    NO_ERROR(rstack_push_rstack(rs13, rs91));
    ASSERT(rstack_empty(rs79) == true);
    ASSERT_RESULT(rstack_front(rs56), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs63, rs2));
    ASSERT_RESULT(rstack_front(rs72), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs46, rs87));
    ASSERT(rstack_empty(rs52) == true);
    NO_ERROR(rstack_write("test_178.fout", rs61));
    ASSERT_RESULT(rstack_front(rs93), false, 0UL);
    NO_ERROR(rstack_write("test_18.fout", rs32));
    NO_ERROR(rstack_push_rstack(rs75, rs59));
    NO_ERROR(rstack_push_rstack(rs72, rs59));
    NO_ERROR(rstack_push_rstack(rs62, rs59));
    NO_ERROR(rstack_push_rstack(rs87, rs64));
    NO_ERROR(rstack_write("test_133.fout", rs49));
    NO_ERROR(rstack_push_rstack(rs97, rs69));
    ASSERT_RESULT(rstack_front(rs40), false, 0UL);
    NO_ERROR(rstack_write("test_74.fout", rs9));
    NO_ERROR(rstack_write("test_125.fout", rs40));
    NO_ERROR(rstack_push_rstack(rs16, rs11));
    NO_ERROR(rstack_push_rstack(rs27, rs0));
    ASSERT_RESULT(rstack_front(rs88), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs98, rs27));
    NO_ERROR(rstack_push_rstack(rs98, rs25));
    NO_ERROR(rstack_write("test_73.fout", rs15));
    NO_ERROR(rstack_push_rstack(rs28, rs12));
    ASSERT_RESULT(rstack_front(rs39), false, 0UL);
    ASSERT_RESULT(rstack_front(rs52), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs35, rs79));
    NO_ERROR(rstack_write("test_53.fout", rs20));
    NO_ERROR(rstack_push_rstack(rs16, rs39));
    NO_ERROR(rstack_push_rstack(rs48, rs5));
    NO_ERROR(rstack_write("test_177.fout", rs58));
    ASSERT_RESULT(rstack_front(rs17), false, 0UL);
    NO_ERROR(rstack_write("test_157.fout", rs59));
    NO_ERROR(rstack_write("test_102.fout", rs94));
    NO_ERROR(rstack_push_rstack(rs44, rs83));
    ASSERT(rstack_empty(rs80) == true);
    NO_ERROR(rstack_push_rstack(rs45, rs41));
    NO_ERROR(rstack_push_rstack(rs33, rs2));
    ASSERT_RESULT(rstack_front(rs87), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs76, rs40));
    NO_ERROR(rstack_push_rstack(rs48, rs85));
    NO_ERROR(rstack_push_rstack(rs91, rs23));
    NO_ERROR(rstack_push_rstack(rs83, rs85));
    ASSERT_RESULT(rstack_front(rs31), false, 0UL);
    NO_ERROR(rstack_write("test_131.fout", rs50));
    NO_ERROR(rstack_push_rstack(rs13, rs18));
    NO_ERROR(rstack_push_rstack(rs93, rs83));
    ASSERT_RESULT(rstack_front(rs81), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs27, rs33));
    NO_ERROR(rstack_push_rstack(rs46, rs41));
    NO_ERROR(rstack_push_rstack(rs19, rs74));
    NO_ERROR(rstack_push_rstack(rs54, rs23));
    NO_ERROR(rstack_push_rstack(rs7, rs35));
    NO_ERROR(rstack_push_rstack(rs49, rs18));
    NO_ERROR(rstack_write("test_192.fout", rs12));
    NO_ERROR(rstack_push_rstack(rs84, rs75));
    NO_ERROR(rstack_push_rstack(rs14, rs5));
    ASSERT_RESULT(rstack_front(rs47), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs50, rs72));
    NO_ERROR(rstack_push_rstack(rs64, rs18));
    NO_ERROR(rstack_push_rstack(rs91, rs37));
    NO_ERROR(rstack_write("test_128.fout", rs16));
    ASSERT(rstack_empty(rs14) == true);
    NO_ERROR(rstack_push_rstack(rs69, rs46));
    ASSERT_RESULT(rstack_front(rs34), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs17, rs12));
    NO_ERROR(rstack_push_rstack(rs0, rs78));
    NO_ERROR(rstack_write("test_83.fout", rs65));
    NO_ERROR(rstack_write("test_150.fout", rs88));
    NO_ERROR(rstack_push_rstack(rs10, rs54));
    ASSERT_RESULT(rstack_front(rs64), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs90, rs37));
    NO_ERROR(rstack_push_rstack(rs60, rs28));
    NO_ERROR(rstack_push_rstack(rs60, rs32));
    NO_ERROR(rstack_push_rstack(rs17, rs20));
    NO_ERROR(rstack_push_rstack(rs96, rs17));
    NO_ERROR(rstack_push_rstack(rs88, rs47));
    NO_ERROR(rstack_push_rstack(rs75, rs81));
    ASSERT_RESULT(rstack_front(rs81), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs93, rs8));
    ASSERT(rstack_empty(rs25) == true);
    NO_ERROR(rstack_write("test_21.fout", rs40));
    ASSERT(rstack_empty(rs62) == true);
    NO_ERROR(rstack_write("test_164.fout", rs68));
    NO_ERROR(rstack_write("test_92.fout", rs93));
    NO_ERROR(rstack_write("test_126.fout", rs97));
    NO_ERROR(rstack_push_rstack(rs47, rs8));
    NO_ERROR(rstack_push_rstack(rs16, rs29));
    ASSERT_RESULT(rstack_front(rs53), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs29, rs91));
    NO_ERROR(rstack_push_rstack(rs75, rs89));
    NO_ERROR(rstack_push_rstack(rs44, rs8));
    NO_ERROR(rstack_write("test_91.fout", rs94));
    NO_ERROR(rstack_write("test_38.fout", rs24));
    NO_ERROR(rstack_write("test_93.fout", rs58));
    NO_ERROR(rstack_push_rstack(rs90, rs1));
    NO_ERROR(rstack_push_rstack(rs63, rs0));
    NO_ERROR(rstack_push_rstack(rs26, rs78));
    ASSERT(rstack_empty(rs25) == true);
    NO_ERROR(rstack_write("test_47.fout", rs49));
    NO_ERROR(rstack_push_rstack(rs59, rs61));
    NO_ERROR(rstack_push_rstack(rs29, rs15));
    NO_ERROR(rstack_write("test_143.fout", rs36));
    NO_ERROR(rstack_push_rstack(rs42, rs65));
    NO_ERROR(rstack_push_rstack(rs47, rs95));
    NO_ERROR(rstack_write("test_29.fout", rs13));
    NO_ERROR(rstack_push_rstack(rs57, rs20));
    NO_ERROR(rstack_write("test_188.fout", rs25));
    NO_ERROR(rstack_write("test_43.fout", rs51));
    NO_ERROR(rstack_push_rstack(rs61, rs2));
    NO_ERROR(rstack_push_rstack(rs86, rs16));
    NO_ERROR(rstack_push_rstack(rs33, rs26));
    ASSERT_RESULT(rstack_front(rs52), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs23));
    ASSERT(rstack_empty(rs94) == true);
    NO_ERROR(rstack_write("test_195.fout", rs48));
    NO_ERROR(rstack_push_rstack(rs84, rs87));
    ASSERT_RESULT(rstack_front(rs74), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs28, rs36));
    NO_ERROR(rstack_write("test_187.fout", rs43));
    ASSERT_RESULT(rstack_front(rs90), false, 0UL);
    ASSERT_RESULT(rstack_front(rs37), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs98, rs77));
    NO_ERROR(rstack_write("test_149.fout", rs5));
    NO_ERROR(rstack_push_rstack(rs66, rs83));
    ASSERT_RESULT(rstack_front(rs97), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs62, rs49));
    ASSERT_RESULT(rstack_front(rs75), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs93, rs76));
    ASSERT(rstack_empty(rs96) == true);
    NO_ERROR(rstack_push_rstack(rs98, rs5));
    NO_ERROR(rstack_write("test_151.fout", rs83));
    ASSERT_RESULT(rstack_front(rs70), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs55, rs94));
    NO_ERROR(rstack_write("test_49.fout", rs11));
    NO_ERROR(rstack_push_rstack(rs80, rs42));
    ASSERT(rstack_empty(rs70) == true);
    NO_ERROR(rstack_write("test_80.fout", rs25));
    NO_ERROR(rstack_write("test_33.fout", rs26));
    NO_ERROR(rstack_write("test_89.fout", rs67));
    NO_ERROR(rstack_push_rstack(rs76, rs87));
    NO_ERROR(rstack_write("test_34.fout", rs38));
    NO_ERROR(rstack_push_rstack(rs40, rs29));
    ASSERT(rstack_empty(rs81) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs49));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    ASSERT_RESULT(rstack_front(rs57), false, 0UL);
    NO_ERROR(rstack_write("test_127.fout", rs44));
    NO_ERROR(rstack_push_rstack(rs16, rs54));
    NO_ERROR(rstack_write("test_189.fout", rs90));
    ASSERT(rstack_empty(rs33) == true);
    ASSERT_RESULT(rstack_front(rs56), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs52, rs32));
    NO_ERROR(rstack_push_rstack(rs77, rs19));
    NO_ERROR(rstack_push_rstack(rs92, rs50));
    NO_ERROR(rstack_push_rstack(rs40, rs59));
    ASSERT_RESULT(rstack_front(rs98), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs67, rs80));
    NO_ERROR(rstack_push_rstack(rs18, rs59));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs32, rs32));
    NO_ERROR(rstack_push_rstack(rs88, rs31));
    NO_ERROR(rstack_push_rstack(rs40, rs84));
    NO_ERROR(rstack_push_rstack(rs51, rs36));
    ASSERT(rstack_empty(rs5) == true);
    NO_ERROR(rstack_push_rstack(rs33, rs84));
    ASSERT_RESULT(rstack_front(rs76), false, 0UL);
    NO_ERROR(rstack_write("test_155.fout", rs12));
    NO_ERROR(rstack_push_rstack(rs36, rs93));
    ASSERT_RESULT(rstack_front(rs19), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs70, rs34));
    NO_ERROR(rstack_push_rstack(rs99, rs20));
    NO_ERROR(rstack_push_rstack(rs7, rs47));
    NO_ERROR(rstack_push_rstack(rs55, rs75));
    NO_ERROR(rstack_push_rstack(rs67, rs15));
    NO_ERROR(rstack_push_rstack(rs44, rs80));
    NO_ERROR(rstack_write("test_154.fout", rs56));
    NO_ERROR(rstack_push_rstack(rs52, rs7));
    ASSERT_RESULT(rstack_front(rs91), false, 0UL);
    ASSERT_RESULT(rstack_front(rs58), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs41, rs86));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs92, rs44));
    NO_ERROR(rstack_write("test_145.fout", rs9));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    NO_ERROR(rstack_write("test_116.fout", rs91));
    NO_ERROR(rstack_push_rstack(rs78, rs69));
    NO_ERROR(rstack_write("test_183.fout", rs53));
    NO_ERROR(rstack_push_rstack(rs43, rs87));
    NO_ERROR(rstack_push_rstack(rs93, rs61));
    NO_ERROR(rstack_push_rstack(rs91, rs56));
    ASSERT(rstack_empty(rs16) == true);
    NO_ERROR(rstack_write("test_191.fout", rs18));
    NO_ERROR(rstack_write("test_156.fout", rs5));
    ASSERT(rstack_empty(rs68) == true);
    NO_ERROR(rstack_push_rstack(rs28, rs80));
    NO_ERROR(rstack_write("test_161.fout", rs34));
    ASSERT_RESULT(rstack_front(rs55), false, 0UL);
    ASSERT(rstack_empty(rs75) == true);
    NO_ERROR(rstack_push_rstack(rs79, rs61));
    NO_ERROR(rstack_push_rstack(rs97, rs37));
    NO_ERROR(rstack_write("test_166.fout", rs7));
    NO_ERROR(rstack_push_rstack(rs81, rs81));
    NO_ERROR(rstack_write("test_85.fout", rs22));
    NO_ERROR(rstack_push_rstack(rs52, rs68));
    NO_ERROR(rstack_push_rstack(rs97, rs45));
    ASSERT_RESULT(rstack_front(rs44), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs55, rs11));
    ASSERT(rstack_empty(rs88) == true);
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs0, rs40));
    NO_ERROR(rstack_write("test_107.fout", rs42));
    NO_ERROR(rstack_write("test_22.fout", rs85));
    NO_ERROR(rstack_push_rstack(rs42, rs52));
    ASSERT(rstack_empty(rs37) == true);
    NO_ERROR(rstack_push_rstack(rs52, rs9));
    NO_ERROR(rstack_push_rstack(rs69, rs31));
    NO_ERROR(rstack_push_rstack(rs98, rs7));
    NO_ERROR(rstack_push_rstack(rs1, rs46));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_write("test_172.fout", rs70));
    ASSERT_RESULT(rstack_front(rs63), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs61, rs78));
    NO_ERROR(rstack_write("test_113.fout", rs42));
    NO_ERROR(rstack_push_rstack(rs12, rs53));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs85, rs90));
    NO_ERROR(rstack_push_rstack(rs70, rs2));
    NO_ERROR(rstack_write("test_5.fout", rs54));
    NO_ERROR(rstack_push_rstack(rs33, rs95));
    NO_ERROR(rstack_push_rstack(rs78, rs75));
    ASSERT(rstack_empty(rs50) == true);
    ASSERT(rstack_empty(rs73) == true);
    NO_ERROR(rstack_push_rstack(rs70, rs26));
    NO_ERROR(rstack_push_rstack(rs22, rs61));
    NO_ERROR(rstack_push_rstack(rs26, rs85));
    ASSERT_RESULT(rstack_front(rs83), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs28, rs8));
    NO_ERROR(rstack_write("test_167.fout", rs98));
    NO_ERROR(rstack_push_rstack(rs14, rs77));
    NO_ERROR(rstack_push_rstack(rs6, rs90));
    NO_ERROR(rstack_push_rstack(rs45, rs96));
    NO_ERROR(rstack_push_rstack(rs32, rs20));
    NO_ERROR(rstack_write("test_16.fout", rs95));
    NO_ERROR(rstack_push_rstack(rs30, rs66));
    NO_ERROR(rstack_push_rstack(rs62, rs10));
    NO_ERROR(rstack_push_rstack(rs48, rs60));
    NO_ERROR(rstack_push_rstack(rs41, rs81));
    NO_ERROR(rstack_push_rstack(rs63, rs8));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs41, rs80));
    NO_ERROR(rstack_push_rstack(rs91, rs14));
    NO_ERROR(rstack_push_rstack(rs24, rs53));
    NO_ERROR(rstack_push_rstack(rs37, rs73));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs53, rs84));
    ASSERT_RESULT(rstack_front(rs92), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs68, rs25));
    NO_ERROR(rstack_write("test_103.fout", rs39));
    NO_ERROR(rstack_push_rstack(rs56, rs53));
    NO_ERROR(rstack_push_rstack(rs32, rs78));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    ASSERT(rstack_empty(rs0) == true);
    NO_ERROR(rstack_push_rstack(rs4, rs75));
    ASSERT_RESULT(rstack_front(rs36), false, 0UL);
    ASSERT_RESULT(rstack_front(rs94), false, 0UL);
    NO_ERROR(rstack_write("test_117.fout", rs55));
    NO_ERROR(rstack_push_rstack(rs56, rs83));
    NO_ERROR(rstack_push_rstack(rs47, rs91));
    NO_ERROR(rstack_push_rstack(rs54, rs37));
    NO_ERROR(rstack_push_rstack(rs90, rs15));
    NO_ERROR(rstack_push_rstack(rs84, rs5));
    NO_ERROR(rstack_push_rstack(rs7, rs19));
    NO_ERROR(rstack_write("test_106.fout", rs79));
    NO_ERROR(rstack_push_rstack(rs0, rs2));
    NO_ERROR(rstack_write("test_101.fout", rs40));
    NO_ERROR(rstack_push_rstack(rs73, rs96));
    NO_ERROR(rstack_push_rstack(rs88, rs26));
    NO_ERROR(rstack_push_rstack(rs6, rs72));
    ASSERT_RESULT(rstack_front(rs45), false, 0UL);
    ASSERT(rstack_empty(rs53) == true);
    NO_ERROR(rstack_push_rstack(rs12, rs6));
    NO_ERROR(rstack_write("test_69.fout", rs57));
    NO_ERROR(rstack_push_rstack(rs4, rs43));
    NO_ERROR(rstack_push_rstack(rs57, rs83));
    ASSERT_RESULT(rstack_front(rs75), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs13, rs46));
    ASSERT_RESULT(rstack_front(rs13), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs2, rs15));
    NO_ERROR(rstack_push_rstack(rs14, rs16));
    NO_ERROR(rstack_push_rstack(rs88, rs66));
    ASSERT(rstack_empty(rs23) == true);
    NO_ERROR(rstack_write("test_105.fout", rs96));
    NO_ERROR(rstack_push_rstack(rs55, rs81));
    ASSERT_RESULT(rstack_front(rs81), false, 0UL);
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    ASSERT_RESULT(rstack_front(rs23), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs30, rs42));
    NO_ERROR(rstack_push_rstack(rs79, rs99));
    ASSERT_RESULT(rstack_front(rs50), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs77, rs81));
    NO_ERROR(rstack_push_rstack(rs1, rs70));
    NO_ERROR(rstack_write("test_124.fout", rs47));
    NO_ERROR(rstack_push_rstack(rs18, rs93));
    NO_ERROR(rstack_write("test_193.fout", rs76));
    ASSERT_RESULT(rstack_front(rs24), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs42, rs19));
    NO_ERROR(rstack_write("test_153.fout", rs62));
    ASSERT_RESULT(rstack_front(rs56), false, 0UL);
    ASSERT(rstack_empty(rs32) == true);
    ASSERT(rstack_empty(rs52) == true);
    NO_ERROR(rstack_push_rstack(rs40, rs53));
    NO_ERROR(rstack_write("test_88.fout", rs64));
    NO_ERROR(rstack_push_rstack(rs12, rs50));
    NO_ERROR(rstack_push_rstack(rs22, rs41));
    NO_ERROR(rstack_push_rstack(rs32, rs85));
    ASSERT_RESULT(rstack_front(rs38), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs41, rs89));
    NO_ERROR(rstack_write("test_180.fout", rs89));
    NO_ERROR(rstack_push_rstack(rs96, rs66));
    NO_ERROR(rstack_push_rstack(rs25, rs31));
    NO_ERROR(rstack_push_rstack(rs91, rs58));
    NO_ERROR(rstack_push_rstack(rs93, rs24));
    NO_ERROR(rstack_push_rstack(rs85, rs34));
    ASSERT(rstack_empty(rs27) == true);
    ASSERT_RESULT(rstack_front(rs59), false, 0UL);
    ASSERT(rstack_empty(rs8) == true);
    NO_ERROR(rstack_push_rstack(rs88, rs72));
    NO_ERROR(rstack_push_rstack(rs19, rs19));
    NO_ERROR(rstack_push_rstack(rs24, rs47));
    NO_ERROR(rstack_write("test_159.fout", rs20));
    NO_ERROR(rstack_push_rstack(rs41, rs29));
    NO_ERROR(rstack_push_rstack(rs60, rs95));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs73, rs3));
    NO_ERROR(rstack_push_rstack(rs73, rs32));
    NO_ERROR(rstack_push_rstack(rs37, rs34));
    NO_ERROR(rstack_write("test_13.fout", rs84));
    ASSERT_RESULT(rstack_front(rs37), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs36, rs58));
    ASSERT_RESULT(rstack_front(rs47), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs87, rs5));
    NO_ERROR(rstack_write("test_87.fout", rs86));
    ASSERT_RESULT(rstack_front(rs95), false, 0UL);
    ASSERT(rstack_empty(rs13) == true);
    NO_ERROR(rstack_write("test_76.fout", rs17));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs70, rs64));
    NO_ERROR(rstack_write("test_37.fout", rs3));
    NO_ERROR(rstack_push_rstack(rs49, rs35));
    NO_ERROR(rstack_push_rstack(rs88, rs66));
    NO_ERROR(rstack_push_rstack(rs18, rs35));
    NO_ERROR(rstack_push_rstack(rs62, rs6));
    NO_ERROR(rstack_push_rstack(rs88, rs78));
    NO_ERROR(rstack_push_rstack(rs50, rs79));
    NO_ERROR(rstack_push_rstack(rs19, rs10));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    NO_ERROR(rstack_write("test_30.fout", rs89));
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs79, rs70));
    NO_ERROR(rstack_push_rstack(rs30, rs13));
    NO_ERROR(rstack_push_rstack(rs27, rs32));
    NO_ERROR(rstack_write("test_4.fout", rs10));
    NO_ERROR(rstack_push_rstack(rs8, rs54));
    NO_ERROR(rstack_push_rstack(rs88, rs79));
    NO_ERROR(rstack_write("test_95.fout", rs8));
    NO_ERROR(rstack_push_rstack(rs82, rs54));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs98, rs4));
    NO_ERROR(rstack_push_rstack(rs72, rs5));
    NO_ERROR(rstack_push_rstack(rs5, rs15));
    NO_ERROR(rstack_push_rstack(rs32, rs43));
    NO_ERROR(rstack_push_rstack(rs82, rs52));
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_write("test_135.fout", rs31));
    ASSERT(rstack_empty(rs90) == true);
    ASSERT_RESULT(rstack_front(rs15), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs81, rs67));
    ASSERT(rstack_empty(rs85) == true);
    NO_ERROR(rstack_write("test_52.fout", rs53));
    NO_ERROR(rstack_write("test_31.fout", rs3));
    ASSERT_RESULT(rstack_front(rs58), false, 0UL);
    NO_ERROR(rstack_write("test_169.fout", rs68));
    NO_ERROR(rstack_push_rstack(rs43, rs4));
    NO_ERROR(rstack_push_rstack(rs54, rs5));
    ASSERT_RESULT(rstack_front(rs69), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs76, rs41));
    NO_ERROR(rstack_push_rstack(rs53, rs18));
    NO_ERROR(rstack_push_rstack(rs65, rs38));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs65, rs84));
    NO_ERROR(rstack_push_rstack(rs6, rs26));
    NO_ERROR(rstack_write("test_84.fout", rs90));
    NO_ERROR(rstack_push_rstack(rs31, rs30));
    NO_ERROR(rstack_push_rstack(rs86, rs77));
    ASSERT_RESULT(rstack_front(rs70), false, 0UL);
    NO_ERROR(rstack_write("test_120.fout", rs14));
    ASSERT(rstack_empty(rs56) == true);
    NO_ERROR(rstack_write("test_132.fout", rs54));
    NO_ERROR(rstack_write("test_111.fout", rs48));
    NO_ERROR(rstack_push_rstack(rs54, rs24));
    ASSERT_RESULT(rstack_front(rs17), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs10, rs3));
    NO_ERROR(rstack_write("test_72.fout", rs91));
    NO_ERROR(rstack_push_rstack(rs61, rs26));
    ASSERT_RESULT(rstack_front(rs2), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs23, rs84));
    NO_ERROR(rstack_push_rstack(rs46, rs51));
    ASSERT_RESULT(rstack_front(rs87), false, 0UL);
    NO_ERROR(rstack_write("test_194.fout", rs20));
    NO_ERROR(rstack_push_rstack(rs85, rs49));
    NO_ERROR(rstack_write("test_179.fout", rs72));
    NO_ERROR(rstack_push_rstack(rs6, rs48));
    ASSERT_RESULT(rstack_front(rs29), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs92, rs24));
    NO_ERROR(rstack_push_rstack(rs95, rs63));
    NO_ERROR(rstack_push_rstack(rs26, rs45));
    ASSERT(rstack_empty(rs72) == true);
    NO_ERROR(rstack_push_rstack(rs18, rs15));
    NO_ERROR(rstack_push_rstack(rs55, rs36));
    NO_ERROR(rstack_push_rstack(rs91, rs35));
    NO_ERROR(rstack_push_rstack(rs14, rs72));
    NO_ERROR(rstack_push_rstack(rs63, rs19));
    ASSERT(rstack_empty(rs77) == true);
    NO_ERROR(rstack_push_rstack(rs26, rs47));
    ASSERT_RESULT(rstack_front(rs77), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs91, rs29));
    ASSERT_RESULT(rstack_front(rs5), false, 0UL);
    NO_ERROR(rstack_write("test_99.fout", rs85));
    NO_ERROR(rstack_push_rstack(rs33, rs26));
    NO_ERROR(rstack_write("test_39.fout", rs64));
    NO_ERROR(rstack_push_rstack(rs5, rs40));
    NO_ERROR(rstack_push_rstack(rs83, rs14));
    NO_ERROR(rstack_push_rstack(rs12, rs63));
    NO_ERROR(rstack_push_rstack(rs7, rs96));
    ASSERT_RESULT(rstack_front(rs51), false, 0UL);
    NO_ERROR(rstack_write("test_67.fout", rs78));
    NO_ERROR(rstack_push_rstack(rs90, rs64));
    NO_ERROR(rstack_push_rstack(rs38, rs47));
    NO_ERROR(rstack_write("test_17.fout", rs3));
    ASSERT_RESULT(rstack_front(rs53), false, 0UL);
    ASSERT(rstack_empty(rs28) == true);
    NO_ERROR(rstack_write("test_60.fout", rs57));
    NO_ERROR(rstack_push_rstack(rs21, rs35));
    ASSERT(rstack_empty(rs34) == true);
    ASSERT_RESULT(rstack_front(rs24), false, 0UL);
    NO_ERROR(rstack_write("test_71.fout", rs45));
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    ASSERT(rstack_empty(rs72) == true);
    NO_ERROR(rstack_write("test_129.fout", rs88));
    ASSERT_RESULT(rstack_front(rs1), false, 0UL);
    ASSERT(rstack_empty(rs78) == true);
    NO_ERROR(rstack_push_rstack(rs8, rs12));
    NO_ERROR(rstack_push_rstack(rs32, rs82));
    NO_ERROR(rstack_push_rstack(rs60, rs25));
    ASSERT_RESULT(rstack_front(rs36), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs91));
    NO_ERROR(rstack_push_rstack(rs60, rs25));
    NO_ERROR(rstack_push_rstack(rs96, rs35));
    ASSERT(rstack_empty(rs76) == true);
    NO_ERROR(rstack_write("test_141.fout", rs95));
    NO_ERROR(rstack_push_rstack(rs53, rs29));
    NO_ERROR(rstack_push_rstack(rs90, rs26));
    NO_ERROR(rstack_write("test_10.fout", rs14));
    NO_ERROR(rstack_push_rstack(rs99, rs59));
    NO_ERROR(rstack_push_rstack(rs21, rs15));
    ASSERT_RESULT(rstack_front(rs98), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs39, rs2));
    NO_ERROR(rstack_push_rstack(rs7, rs40));
    NO_ERROR(rstack_push_rstack(rs50, rs3));
    ASSERT_RESULT(rstack_front(rs95), false, 0UL);
    ASSERT(rstack_empty(rs37) == true);
    NO_ERROR(rstack_push_rstack(rs82, rs83));
    NO_ERROR(rstack_push_rstack(rs88, rs93));
    NO_ERROR(rstack_push_rstack(rs77, rs61));
    NO_ERROR(rstack_push_rstack(rs0, rs22));
    ASSERT_RESULT(rstack_front(rs18), false, 0UL);
    NO_ERROR(rstack_write("test_70.fout", rs63));
    NO_ERROR(rstack_push_rstack(rs35, rs26));
    NO_ERROR(rstack_write("test_0.fout", rs51));
    ASSERT_RESULT(rstack_front(rs33), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs28, rs93));
    NO_ERROR(rstack_push_rstack(rs48, rs37));
    NO_ERROR(rstack_push_rstack(rs9, rs38));
    NO_ERROR(rstack_push_rstack(rs87, rs71));
    NO_ERROR(rstack_push_rstack(rs88, rs19));
    NO_ERROR(rstack_push_rstack(rs69, rs6));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    ASSERT_RESULT(rstack_front(rs22), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs15, rs94));
    NO_ERROR(rstack_push_rstack(rs5, rs79));
    NO_ERROR(rstack_push_rstack(rs41, rs28));
    NO_ERROR(rstack_write("test_81.fout", rs37));
    NO_ERROR(rstack_push_rstack(rs9, rs25));
    NO_ERROR(rstack_write("test_168.fout", rs83));
    ASSERT_RESULT(rstack_front(rs46), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs22, rs97));
    NO_ERROR(rstack_push_rstack(rs38, rs92));
    ASSERT_RESULT(rstack_front(rs84), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs5, rs37));
    ASSERT_RESULT(rstack_front(rs50), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs24, rs69));
    ASSERT_RESULT(rstack_front(rs77), false, 0UL);
    ASSERT_RESULT(rstack_front(rs57), false, 0UL);
    NO_ERROR(rstack_write("test_140.fout", rs91));
    NO_ERROR(rstack_push_rstack(rs65, rs40));
    NO_ERROR(rstack_push_rstack(rs25, rs91));
    ASSERT_RESULT(rstack_front(rs95), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs9, rs64));
    NO_ERROR(rstack_push_rstack(rs47, rs33));
    NO_ERROR(rstack_push_rstack(rs20, rs4));
    NO_ERROR(rstack_write("test_3.fout", rs24));
    ASSERT_RESULT(rstack_front(rs4), false, 0UL);
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs24, rs93));
    NO_ERROR(rstack_write("test_78.fout", rs75));
    NO_ERROR(rstack_push_rstack(rs62, rs76));
    NO_ERROR(rstack_write("test_65.fout", rs33));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    NO_ERROR(rstack_write("test_15.fout", rs25));
    ASSERT(rstack_empty(rs73) == true);
    NO_ERROR(rstack_write("test_59.fout", rs20));
    ASSERT_RESULT(rstack_front(rs72), false, 0UL);
    NO_ERROR(rstack_write("test_7.fout", rs58));
    NO_ERROR(rstack_push_rstack(rs92, rs79));
    NO_ERROR(rstack_push_rstack(rs58, rs35));
    NO_ERROR(rstack_push_rstack(rs31, rs24));
    NO_ERROR(rstack_write("test_175.fout", rs91));
    NO_ERROR(rstack_push_rstack(rs78, rs89));
    NO_ERROR(rstack_push_rstack(rs36, rs3));
    NO_ERROR(rstack_push_rstack(rs78, rs42));
    NO_ERROR(rstack_push_rstack(rs61, rs29));
    NO_ERROR(rstack_write("test_139.fout", rs19));
    NO_ERROR(rstack_push_rstack(rs45, rs27));
    NO_ERROR(rstack_write("test_63.fout", rs58));
    NO_ERROR(rstack_write("test_174.fout", rs52));
    ASSERT_RESULT(rstack_front(rs92), false, 0UL);
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs8, rs14));
    NO_ERROR(rstack_write("test_186.fout", rs39));
    ASSERT(rstack_empty(rs19) == true);
    NO_ERROR(rstack_push_rstack(rs64, rs68));
    NO_ERROR(rstack_write("test_134.fout", rs64));
    NO_ERROR(rstack_push_rstack(rs83, rs81));
    NO_ERROR(rstack_push_rstack(rs1, rs97));
    NO_ERROR(rstack_push_rstack(rs82, rs97));
    NO_ERROR(rstack_write("test_104.fout", rs87));
    ASSERT_RESULT(rstack_front(rs11), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs17, rs99));
    ASSERT_RESULT(rstack_front(rs8), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs31, rs17));
    ASSERT_RESULT(rstack_front(rs86), false, 0UL);
    ASSERT_RESULT(rstack_front(rs22), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs21, rs9));
    ASSERT_RESULT(rstack_front(rs6), false, 0UL);
    NO_ERROR(rstack_write("test_118.fout", rs23));
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    ASSERT_RESULT(rstack_front(rs79), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs55, rs78));
    NO_ERROR(rstack_push_rstack(rs89, rs39));
    NO_ERROR(rstack_push_rstack(rs79, rs38));
    ASSERT(rstack_empty(rs97) == true);
    NO_ERROR(rstack_push_rstack(rs69, rs53));
    ASSERT_RESULT(rstack_front(rs53), false, 0UL);
    ASSERT_RESULT(rstack_front(rs13), false, 0UL);
    NO_ERROR(rstack_write("test_112.fout", rs33));
    NO_ERROR(rstack_push_rstack(rs44, rs57));
    NO_ERROR(rstack_push_rstack(rs43, rs52));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    NO_ERROR(rstack_write("test_58.fout", rs65));
    NO_ERROR(rstack_write("test_79.fout", rs2));
    NO_ERROR(rstack_write("test_50.fout", rs89));
    ASSERT_RESULT(rstack_front(rs43), false, 0UL);
    NO_ERROR(rstack_write("test_163.fout", rs85));
    NO_ERROR(rstack_push_rstack(rs61, rs70));
    NO_ERROR(rstack_push_rstack(rs22, rs92));
    NO_ERROR(rstack_write("test_130.fout", rs45));
    NO_ERROR(rstack_push_rstack(rs16, rs94));
    NO_ERROR(rstack_push_rstack(rs46, rs39));
    ASSERT_RESULT(rstack_front(rs19), false, 0UL);
    NO_ERROR(rstack_write("test_86.fout", rs95));
    NO_ERROR(rstack_push_rstack(rs32, rs94));
    NO_ERROR(rstack_push_rstack(rs37, rs58));
    NO_ERROR(rstack_push_rstack(rs76, rs47));
    ASSERT_RESULT(rstack_front(rs99), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs82, rs74));
    NO_ERROR(rstack_write("test_64.fout", rs18));
    NO_ERROR(rstack_write("test_115.fout", rs66));
    ASSERT_RESULT(rstack_front(rs36), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs70, rs85));
    NO_ERROR(rstack_push_rstack(rs90, rs26));
    NO_ERROR(rstack_push_rstack(rs45, rs80));
    NO_ERROR(rstack_write("test_40.fout", rs61));
    NO_ERROR(rstack_push_rstack(rs16, rs85));
    NO_ERROR(rstack_write("test_46.fout", rs38));
    NO_ERROR(rstack_push_rstack(rs32, rs72));
    NO_ERROR(rstack_push_rstack(rs20, rs48));
    NO_ERROR(rstack_write("test_171.fout", rs99));
    NO_ERROR(rstack_push_rstack(rs81, rs12));
    NO_ERROR(rstack_push_rstack(rs45, rs91));
    ASSERT(rstack_empty(rs14) == true);
    NO_ERROR(rstack_write("test_82.fout", rs65));
    NO_ERROR(rstack_push_rstack(rs93, rs99));
    ASSERT_RESULT(rstack_front(rs88), false, 0UL);
    NO_ERROR(rstack_write("test_173.fout", rs64));
    ASSERT_RESULT(rstack_front(rs96), false, 0UL);
    NO_ERROR(rstack_write("test_184.fout", rs12));
    NO_ERROR(rstack_write("test_12.fout", rs33));
    NO_ERROR(rstack_push_rstack(rs54, rs27));
    NO_ERROR(rstack_push_rstack(rs67, rs10));
    NO_ERROR(rstack_push_rstack(rs75, rs55));
    ASSERT(rstack_empty(rs97) == true);
    NO_ERROR(rstack_write("test_94.fout", rs61));
    NO_ERROR(rstack_push_rstack(rs21, rs8));
    NO_ERROR(rstack_push_rstack(rs90, rs65));
    NO_ERROR(rstack_write("test_121.fout", rs86));
    NO_ERROR(rstack_push_rstack(rs11, rs61));
    ASSERT(rstack_empty(rs85) == true);
    NO_ERROR(rstack_push_rstack(rs0, rs91));
    NO_ERROR(rstack_push_rstack(rs35, rs24));
    NO_ERROR(rstack_push_rstack(rs98, rs59));
    ASSERT_RESULT(rstack_front(rs41), false, 0UL);
    ASSERT_RESULT(rstack_front(rs78), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs26, rs64));
    ASSERT_RESULT(rstack_front(rs22), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs85, rs84));
    NO_ERROR(rstack_push_rstack(rs83, rs24));
    NO_ERROR(rstack_push_rstack(rs27, rs72));
    ASSERT(rstack_empty(rs3) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs85));
    NO_ERROR(rstack_write("test_42.fout", rs26));
    NO_ERROR(rstack_push_rstack(rs76, rs60));
    ASSERT_RESULT(rstack_front(rs24), false, 0UL);
    NO_ERROR(rstack_write("test_190.fout", rs20));
    ASSERT(rstack_empty(rs66) == true);
    NO_ERROR(rstack_write("test_25.fout", rs57));
    NO_ERROR(rstack_push_rstack(rs10, rs73));
    NO_ERROR(rstack_push_rstack(rs88, rs7));
    NO_ERROR(rstack_write("test_27.fout", rs23));
    NO_ERROR(rstack_push_rstack(rs56, rs11));
    NO_ERROR(rstack_write("test_197.fout", rs53));
    NO_ERROR(rstack_push_rstack(rs23, rs4));
    NO_ERROR(rstack_push_rstack(rs47, rs39));
    NO_ERROR(rstack_write("test_165.fout", rs12));
    NO_ERROR(rstack_write("test_90.fout", rs13));
    NO_ERROR(rstack_push_rstack(rs35, rs21));
    NO_ERROR(rstack_push_rstack(rs58, rs75));
    NO_ERROR(rstack_push_rstack(rs89, rs16));
    NO_ERROR(rstack_write("test_123.fout", rs20));
    ASSERT(rstack_empty(rs94) == true);
    ASSERT_RESULT(rstack_front(rs81), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs77, rs81));
    NO_ERROR(rstack_write("test_56.fout", rs23));
    NO_ERROR(rstack_push_rstack(rs14, rs59));
    NO_ERROR(rstack_push_rstack(rs21, rs6));
    NO_ERROR(rstack_push_rstack(rs3, rs46));
    NO_ERROR(rstack_push_rstack(rs85, rs79));
    ASSERT_RESULT(rstack_front(rs19), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs24, rs71));
    NO_ERROR(rstack_push_rstack(rs60, rs97));
    NO_ERROR(rstack_push_rstack(rs73, rs39));
    NO_ERROR(rstack_write("test_51.fout", rs19));
    ASSERT_RESULT(rstack_front(rs14), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs32, rs88));
    ASSERT_RESULT(rstack_front(rs78), false, 0UL);
    NO_ERROR(rstack_write("test_144.fout", rs75));
    NO_ERROR(rstack_push_rstack(rs42, rs41));
    NO_ERROR(rstack_push_rstack(rs47, rs18));
    NO_ERROR(rstack_push_rstack(rs88, rs48));
    ASSERT_RESULT(rstack_front(rs51), false, 0UL);
    ASSERT_RESULT(rstack_front(rs9), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs28, rs85));
    NO_ERROR(rstack_push_rstack(rs83, rs46));
    NO_ERROR(rstack_push_rstack(rs71, rs53));
    ASSERT_RESULT(rstack_front(rs66), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs53, rs43));
    NO_ERROR(rstack_write("test_45.fout", rs40));
    NO_ERROR(rstack_push_rstack(rs51, rs4));
    ASSERT_RESULT(rstack_front(rs56), false, 0UL);
    ASSERT_RESULT(rstack_front(rs45), false, 0UL);
    ASSERT(rstack_empty(rs16) == true);
    NO_ERROR(rstack_write("test_152.fout", rs62));
    NO_ERROR(rstack_write("test_48.fout", rs83));
    ASSERT_RESULT(rstack_front(rs12), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs65, rs58));
    NO_ERROR(rstack_push_rstack(rs89, rs46));
    NO_ERROR(rstack_write("test_2.fout", rs37));
    NO_ERROR(rstack_write("test_41.fout", rs28));
    NO_ERROR(rstack_write("test_119.fout", rs24));
    ASSERT(rstack_empty(rs17) == true);
    ASSERT(rstack_empty(rs51) == true);
    ASSERT_RESULT(rstack_front(rs67), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs29, rs86));
    NO_ERROR(rstack_write("test_198.fout", rs52));
    ASSERT(rstack_empty(rs62) == true);
    NO_ERROR(rstack_write("test_182.fout", rs64));
    NO_ERROR(rstack_push_rstack(rs0, rs45));
    ASSERT_RESULT(rstack_front(rs75), false, 0UL);
    ASSERT_RESULT(rstack_front(rs99), false, 0UL);
    ASSERT_RESULT(rstack_front(rs16), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs81, rs94));
    NO_ERROR(rstack_push_rstack(rs50, rs42));
    NO_ERROR(rstack_push_rstack(rs83, rs7));
    NO_ERROR(rstack_push_rstack(rs82, rs20));
    ASSERT_RESULT(rstack_front(rs22), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs61, rs42));
    ASSERT(rstack_empty(rs32) == true);
    NO_ERROR(rstack_push_rstack(rs38, rs2));
    NO_ERROR(rstack_push_rstack(rs45, rs48));
    ASSERT_RESULT(rstack_front(rs78), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs48, rs38));
    ASSERT_RESULT(rstack_front(rs73), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs16, rs12));
    NO_ERROR(rstack_push_rstack(rs36, rs42));
    ASSERT(rstack_empty(rs30) == true);
    NO_ERROR(rstack_push_rstack(rs82, rs35));
    NO_ERROR(rstack_push_rstack(rs30, rs96));
    ASSERT_RESULT(rstack_front(rs66), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs75, rs14));
    NO_ERROR(rstack_push_rstack(rs13, rs16));
    NO_ERROR(rstack_write("test_68.fout", rs84));
    NO_ERROR(rstack_push_rstack(rs68, rs46));
    NO_ERROR(rstack_push_rstack(rs99, rs47));
    ASSERT_RESULT(rstack_front(rs69), false, 0UL);
    NO_ERROR(rstack_write("test_28.fout", rs0));
    NO_ERROR(rstack_write("test_35.fout", rs57));
    NO_ERROR(rstack_write("test_110.fout", rs38));
    NO_ERROR(rstack_push_rstack(rs5, rs7));
    ASSERT_RESULT(rstack_front(rs47), false, 0UL);
    NO_ERROR(rstack_write("test_6.fout", rs65));
    ASSERT(rstack_empty(rs72) == true);
    NO_ERROR(rstack_push_rstack(rs19, rs95));
    NO_ERROR(rstack_push_rstack(rs2, rs87));
    ASSERT_RESULT(rstack_front(rs25), false, 0UL);
    NO_ERROR(rstack_write("test_108.fout", rs87));
    NO_ERROR(rstack_push_rstack(rs48, rs52));
    NO_ERROR(rstack_push_rstack(rs27, rs77));
    ASSERT(rstack_empty(rs16) == true);
    ASSERT(rstack_empty(rs29) == true);
    ASSERT(rstack_empty(rs49) == true);
    NO_ERROR(rstack_push_rstack(rs49, rs80));
    NO_ERROR(rstack_push_rstack(rs17, rs34));
    NO_ERROR(rstack_push_rstack(rs62, rs16));
    NO_ERROR(rstack_write("test_147.fout", rs53));
    ASSERT(rstack_empty(rs64) == true);
    NO_ERROR(rstack_push_rstack(rs98, rs55));
    NO_ERROR(rstack_push_rstack(rs45, rs92));
    NO_ERROR(rstack_push_rstack(rs49, rs90));
    NO_ERROR(rstack_write("test_20.fout", rs96));
    ASSERT_RESULT(rstack_front(rs71), false, 0UL);
    ASSERT_RESULT(rstack_front(rs48), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs25, rs52));
    NO_ERROR(rstack_write("test_196.fout", rs64));
    NO_ERROR(rstack_write("test_24.fout", rs61));
    NO_ERROR(rstack_write("test_36.fout", rs19));
    NO_ERROR(rstack_write("test_181.fout", rs26));
    NO_ERROR(rstack_write("test_146.fout", rs28));
    NO_ERROR(rstack_push_rstack(rs46, rs68));
    NO_ERROR(rstack_push_rstack(rs3, rs18));
    NO_ERROR(rstack_push_rstack(rs34, rs39));
    NO_ERROR(rstack_push_rstack(rs67, rs18));
    NO_ERROR(rstack_push_rstack(rs16, rs34));
    NO_ERROR(rstack_push_rstack(rs70, rs58));
    ASSERT_RESULT(rstack_front(rs7), false, 0UL);
    NO_ERROR(rstack_write("test_55.fout", rs83));
    ASSERT_RESULT(rstack_front(rs67), false, 0UL);
    ASSERT_RESULT(rstack_front(rs19), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs30, rs6));
    NO_ERROR(rstack_push_rstack(rs93, rs5));
    NO_ERROR(rstack_push_rstack(rs3, rs30));
    NO_ERROR(rstack_push_rstack(rs80, rs31));
    NO_ERROR(rstack_push_rstack(rs63, rs33));
    NO_ERROR(rstack_push_rstack(rs86, rs22));
    NO_ERROR(rstack_push_rstack(rs69, rs38));
    ASSERT_RESULT(rstack_front(rs10), false, 0UL);
    ASSERT(rstack_empty(rs54) == true);
    NO_ERROR(rstack_push_rstack(rs30, rs30));
    NO_ERROR(rstack_write("test_122.fout", rs45));
    NO_ERROR(rstack_push_rstack(rs17, rs12));
    NO_ERROR(rstack_push_rstack(rs70, rs56));
    NO_ERROR(rstack_push_rstack(rs86, rs97));
    ASSERT_RESULT(rstack_front(rs87), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs53, rs95));
    NO_ERROR(rstack_write("test_158.fout", rs82));
    NO_ERROR(rstack_push_rstack(rs19, rs89));
    ASSERT_RESULT(rstack_front(rs50), false, 0UL);
    NO_ERROR(rstack_push_rstack(rs83, rs97));
    NO_ERROR(rstack_push_rstack(rs8, rs54));
    NO_ERROR(rstack_push_rstack(rs92, rs2));
    NO_ERROR(rstack_push_rstack(rs41, rs66));
    NO_ERROR(rstack_push_rstack(rs73, rs49));
    NO_ERROR(rstack_write("test_100.fout", rs16));
    NO_ERROR(rstack_push_rstack(rs98, rs35));
    NO_ERROR(rstack_push_rstack(rs63, rs62));
    NO_ERROR(rstack_push_rstack(rs1, rs87));
    NO_ERROR(rstack_push_rstack(rs82, rs4));
    NO_ERROR(rstack_push_rstack(rs0, rs42));
    NO_ERROR(rstack_push_rstack(rs87, rs20));
    NO_ERROR(rstack_push_rstack(rs27, rs48));
    NO_ERROR(rstack_push_rstack(rs72, rs19));
    NO_ERROR(rstack_push_rstack(rs84, rs77));
    ASSERT(rstack_empty(rs81) == true);
    NO_ERROR(rstack_push_rstack(rs86, rs43));
    NO_ERROR(rstack_write("test_185.fout", rs60));
    NO_ERROR(rstack_write("test_96.fout", rs85));
    rstack_delete(rs0);
    rstack_delete(rs1);
    rstack_delete(rs2);
    rstack_delete(rs3);
    rstack_delete(rs4);
    rstack_delete(rs5);
    rstack_delete(rs6);
    rstack_delete(rs7);
    rstack_delete(rs8);
    rstack_delete(rs9);
    rstack_delete(rs10);
    rstack_delete(rs11);
    rstack_delete(rs12);
    rstack_delete(rs13);
    rstack_delete(rs14);
    rstack_delete(rs15);
    rstack_delete(rs16);
    rstack_delete(rs17);
    rstack_delete(rs18);
    rstack_delete(rs19);
    rstack_delete(rs20);
    rstack_delete(rs21);
    rstack_delete(rs22);
    rstack_delete(rs23);
    rstack_delete(rs24);
    rstack_delete(rs25);
    rstack_delete(rs26);
    rstack_delete(rs27);
    rstack_delete(rs28);
    rstack_delete(rs29);
    rstack_delete(rs30);
    rstack_delete(rs31);
    rstack_delete(rs32);
    rstack_delete(rs33);
    rstack_delete(rs34);
    rstack_delete(rs35);
    rstack_delete(rs36);
    rstack_delete(rs37);
    rstack_delete(rs38);
    rstack_delete(rs39);
    rstack_delete(rs40);
    rstack_delete(rs41);
    rstack_delete(rs42);
    rstack_delete(rs43);
    rstack_delete(rs44);
    rstack_delete(rs45);
    rstack_delete(rs46);
    rstack_delete(rs47);
    rstack_delete(rs48);
    rstack_delete(rs49);
    rstack_delete(rs50);
    rstack_delete(rs51);
    rstack_delete(rs52);
    rstack_delete(rs53);
    rstack_delete(rs54);
    rstack_delete(rs55);
    rstack_delete(rs56);
    rstack_delete(rs57);
    rstack_delete(rs58);
    rstack_delete(rs59);
    rstack_delete(rs60);
    rstack_delete(rs61);
    rstack_delete(rs62);
    rstack_delete(rs63);
    rstack_delete(rs64);
    rstack_delete(rs65);
    rstack_delete(rs66);
    rstack_delete(rs67);
    rstack_delete(rs68);
    rstack_delete(rs69);
    rstack_delete(rs70);
    rstack_delete(rs71);
    rstack_delete(rs72);
    rstack_delete(rs73);
    rstack_delete(rs74);
    rstack_delete(rs75);
    rstack_delete(rs76);
    rstack_delete(rs77);
    rstack_delete(rs78);
    rstack_delete(rs79);
    rstack_delete(rs80);
    rstack_delete(rs81);
    rstack_delete(rs82);
    rstack_delete(rs83);
    rstack_delete(rs84);
    rstack_delete(rs85);
    rstack_delete(rs86);
    rstack_delete(rs87);
    rstack_delete(rs88);
    rstack_delete(rs89);
    rstack_delete(rs90);
    rstack_delete(rs91);
    rstack_delete(rs92);
    rstack_delete(rs93);
    rstack_delete(rs94);
    rstack_delete(rs95);
    rstack_delete(rs96);
    rstack_delete(rs97);
    rstack_delete(rs98);
    rstack_delete(rs99);
        
        return PASS;
}
